### ISSUE TITLE
PropertyNamingPolicy doesn't work on Insert and Update

### ISSUE THREAD

**Issue by hidim** [IEvangelist/azure-cosmos-dotnet-repository#105]
My SerilizationOptions setting is showed below.

                options.SerializationOptions = new Microsoft.Azure.CosmosRepository.Options.RepositorySerializationOptions
                {
                    IgnoreNullValues = true,
                    PropertyNamingPolicy = Microsoft.Azure.Cosmos.CosmosPropertyNamingPolicy.Default,
                    Indented = true,
                };

I can sucessfully select values but when I try to update or insert new ones, they are updated in Cosmos db with CamelCase naming settings.

I cannot select these newly inserted values too because of My NamingPolicy is "Default".

I even tried to use JsonProperty but it didn't worked either. 

![image](https://user-images.githubusercontent.com/3491112/131673478-e2d04a66-b3be-4b32-ab2c-8f3d27070dec.png)
![image](https://user-images.githubusercontent.com/3491112/131673523-ba308b63-6677-401a-8fde-455ecce3b42b.png)

**Comment by hidim** [comment]
I've fixed the solution by adding naming properties on appsettings.json.
services.AddCosmosRepository specified properties didn't worked.

**Comment by IEvangelist** [comment]
Could you please share the exact code that didn't work versus the code that does?

**Comment by hidim** [comment]
services.AddCosmosRepository(options =>
            {
                options.CosmosConnectionString = this.configuration.GetValue<string>("CosmosConnectionString");
                options.DatabaseId = "Master1";
                options.ContainerPerItemType = true;
                options.OptimizeBandwidth = true;
                options.SerializationOptions = new Microsoft.Azure.CosmosRepository.Options.RepositorySerializationOptions
                {
                    IgnoreNullValues = true,
                    PropertyNamingPolicy = Microsoft.Azure.Cosmos.CosmosPropertyNamingPolicy.Default,
                    Indented = true,
                };
            });

I've transferred this tp appsettings.json like this;

  "RepositoryOptions": {
    "CosmosConnectionString": "***",
    "DatabaseId": "Master1",
    "ContainerPerItemType": true,
    "OptimizeBandwidth": true,
    "SerializationOptions": {
      "IgnoreNullValues": true,
      "PropertyNamingPolicy": "Default",
      "Intented": true
    }
  },

**Comment by mumby0168** [comment]
> ```
>         services.AddCosmosRepository(options =>
>         {
>             options.CosmosConnectionString = this.configuration.GetValue<string>("CosmosConnectionString");
>             options.DatabaseId = "Master1";
>             options.ContainerPerItemType = true;
>             options.OptimizeBandwidth = true;
>             options.SerializationOptions = new Microsoft.Azure.CosmosRepository.Options.RepositorySerializationOptions
>             {
>                 IgnoreNullValues = true,
>                 PropertyNamingPolicy = Microsoft.Azure.Cosmos.CosmosPropertyNamingPolicy.Default,
>                 Indented = true,
>             };
>         });
> ```
> 
> I've transferred this tp appsettings.json like this;
> 
> "RepositoryOptions": {
> "CosmosConnectionString": "***",
> "DatabaseId": "Master1",
> "ContainerPerItemType": true,
> "OptimizeBandwidth": true,
> "SerializationOptions": {
> "IgnoreNullValues": true,
> "PropertyNamingPolicy": "Default",
> "Intented": true
> }
> },

Hi there I do not think you can apply config on the serialisation options in that way I think these need to come via code.

**Comment by mumby0168** [comment]
Hey @hidim any update on this was it still a problem or can we close this issue?

**Comment by hidim** [comment]
@mumby0168 haven't tested AddCosmosRepository options but appsettings.json configuration resolved my problem. I think we can close this issue.
