### ISSUE TITLE
Ability to set CosmosClientOptions - helpful with local Docker Emulator usage

### ISSUE THREAD

**Issue by totalitydevelopment** [IEvangelist/azure-cosmos-dotnet-repository#126]
**Is your feature request related to a problem? Please describe.**
When attempting to use the repository in a containerised application the following error occurs:
"System.InvalidOperationException: Cannot create Collection Information for Drivers in database drivers with lease leases in database drivers : The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception."

The lack of configurability is preventing me from using this really useful repository as part of our microservice solution

**Describe the solution you'd like**
Looking at this link it seems we can override certificate config, so the ability pass these options through (or the repo's own version of) would be a suggestion?
https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#disable-ssl-validation
```
CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
{
    HttpClientFactory = () =>
    {
        HttpMessageHandler httpMessageHandler = new HttpClientHandler()
        {
            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        };

        return new HttpClient(httpMessageHandler);
    },
    ConnectionMode = ConnectionMode.Gateway
};


CosmosClient client = new CosmosClient(endpoint, authKey, cosmosClientOptions);
```

**Additional context**
Unless there is currently a way of achieving local, containerised development already within the project I'm unaware of, I think solving this problem would open  up the repository to another level of software.

**Comment by IEvangelist** [comment]
Hi @totalitydevelopment - this is probably something that could be added. If you have any available cycles, we'd love your contributions. Please feel free to create a PR to add this functionality, and reference this issue in the PR. I've mark this issue as `up-for-grabs`. Thanks again.

**Comment by totalitydevelopment** [comment]
Thanks for the response @IEvangelist. I think I've found it.

In Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions:
```
public static IServiceCollection AddCosmosRepository(
            this IServiceCollection services,
            Action<RepositoryOptions> setupAction = default,
            Action<CosmosClientOptions> additionSetupAction = default)
```

I will give this a run out now and let you know if it isn't resolving the requirement (and look into a PR).

Apologies for wasting your time.

**Comment by IEvangelist** [comment]
No worries whatsoever, if you couldn't find it - others may have not been able to either. This is great, we should probably add to the README.md. Thank you

**Comment by mumby0168** [comment]
Hey, @IEvangelist @totalitydevelopment Yes, that extension method should do the trick, happy to add more configuration options if you find you need it 👍  I agree with @IEvangelist we need to work on the README.md to reflect this sort of stuff.

**Comment by mumby0168** [comment]
@totalitydevelopment really cool to hear you are considering using this for your microservice project, If you wouldn't mind, what is your domain? I am currently using this for warehousing and it's working a treat 👍

**Comment by totalitydevelopment** [comment]
@mumby0168 we're using a load of new technologies within the team for a greenfield project.

Our first run at a microservice architecture using K8, Docker, Azure Functions and the like. Also a first run with Cosmos and we found ourselves writing a lot of repetitive code.

I watched part of the Cosmos Conf and saw @IEvangelist video so dived straight onto it as it saves sooo much repetition in our cosmos related data layer.

Great work guys.

**Comment by mumby0168** [comment]
> @mumby0168 we're using a load of new technologies within the team for a greenfield project.
> 
> Our first run at a microservice architecture using K8, Docker, Azure Functions and the like. Also a first run with Cosmos and we found ourselves writing a lot of repetitive code.
> 
> I watched part of the Cosmos Conf and saw @IEvangelist video so dived straight onto it as it saves sooo much repetition in our cosmos related data layer.
> 
> Great work guys.

@totalitydevelopment we were in a very similar position this has been great for us 👍

**Comment by totalitydevelopment** [comment]
> > @mumby0168 we're using a load of new technologies within the team for a greenfield project.
> > Our first run at a microservice architecture using K8, Docker, Azure Functions and the like. Also a first run with Cosmos and we found ourselves writing a lot of repetitive code.
> > I watched part of the Cosmos Conf and saw @IEvangelist video so dived straight onto it as it saves sooo much repetition in our cosmos related data layer.
> > Great work guys.
> 
> @totalitydevelopment we were in a very similar position this has been great for us 👍 Hope all goes well

Likewise, good luck with the project.

**Comment by mumby0168** [comment]
Thanks, @totalitydevelopment did the above options solve the issues you were having?

**Comment by totalitydevelopment** [comment]
> 
> 
> Thanks, @totalitydevelopment did the above options solve the issues you were having?

I believe so @mumby0168 but am still having other issues just wanted to be sure before closing. Will let you know one way or the other but definately looking promising.

**Comment by totalitydevelopment** [comment]
@mumby0168 this is what I ended up with after being able to override the cosmos client options as discussed. 
```
s.AddCosmosRepository(options =>
          {
              ... options setup
          },
          cosmosClientOptions => //todo this absolutely only needs to occur in dev mode!!!
          {
              cosmosClientOptions.HttpClientFactory = () =>
                  {
                      HttpMessageHandler httpMessageHandler = new HttpClientHandler()
                      {
                          ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                      };
                      return new HttpClient(httpMessageHandler);
                  };

              cosmosClientOptions.ConnectionMode = ConnectionMode.Gateway;
          }
```

**Comment by totalitydevelopment** [comment]
Closing this off as my initial requirement is already open to use.

**Comment by MattHartz** [comment]
Hi all, I am trying to have a  dotnet app communicate to my cosmosdb both running on docker containers. It seems like there is still a disconnect where my dotnet app is trying to establish a connection to localhost (127.0.0.1) then the ip address.

here is roughly where i based my docker compose off of.

https://stackoverflow.com/questions/75543145/how-to-access-cosmosdb-docker-container-from-another-container
