### ISSUE TITLE
Bulk Update

### ISSUE THREAD

**Issue by mustafarabie** [IEvangelist/azure-cosmos-dotnet-repository#127]
Currently only bulk create is supported by the package, where an IEnumerable<TItem> can be passed to CreateAsync function and items are added to the cosmos container. This functionality is missing for UpdateAsync. It comes in handy when you have multiple items that needs to be added and increases performance.

Add a new UpdateAsync function that accepts IEnumerable<TItem> and updates the cosmos container values
UpdateAsync(IEnumerable<TItem> values, CancellationToken cancellationToken = default);

I cloned the repo and added the function locally on my machine, tested and working as expected. 

If this is a feature that you see valuable, I can create a PR for review.

**Comment by mumby0168** [comment]
> Currently only bulk create is supported by the package, where an IEnumerable can be passed to CreateAsync function and items are added to the cosmos container. This functionality is missing for UpdateAsync. It comes in handy when you have multiple items that needs to be added and increases performance.
> 
> Add a new UpdateAsync function that accepts IEnumerable and updates the cosmos container values UpdateAsync(IEnumerable values, CancellationToken cancellationToken = default);
> 
> I cloned the repo and added the function locally on my machine, tested and working as expected.
> 
> If this is a feature that you see valuable, I can create a PR for review.

Hi @mustafarabie I like the idea! The only thing I would try is getting a list of tasks back from an `var tasks = items.Select(x => _repository.UpdateAsync(x).AsTask());` call and then use those tasks inside a `Task.WhenAll(tasks)` and see if that achieves the same thing?

**Comment by IEvangelist** [comment]
Hi @mustafarabie - I too like this idea. Please send over a PR and reference this issue in it. Thanks

**Comment by mustafarabie** [comment]
Currently only bulk create is supported by the package, where an IEnumerable can be passed to CreateAsync function and items are added to the cosmos container. This functionality is missing for UpdateAsync. It comes in handy when you have multiple items that needs to be added and increases performance.
> > Add a new UpdateAsync function that accepts IEnumerable and updates the cosmos container values UpdateAsync(IEnumerable values, CancellationToken cancellationToken = default);
> > I cloned the repo and added the function locally on my machine, tested and working as expected.
> > If this is a feature that you see valuable, I can create a PR for review.
> 
> Hi @mustafarabie I like the idea! The only thing I would try is getting a list of tasks back from an `var tasks = items.Select(x => _repository.UpdateAsync(x).AsTask());` call and then use those tasks inside a `Task.WhenAll(tasks)` and see if that achieves the same thing?

I followed the same logic as of the CreateAsync.

**Comment by mustafarabie** [comment]
@IEvangelist trying to push my branch to create a PR, but I am getting an error that I don't have write access to the repo.

Thanks

**Comment by IEvangelist** [comment]
You have to create a fork of this repo under your account, and then push to your fork. From your fork, you'll then create a PR into this repo. Does that make sense? In your fork you'll create a feature branch, see [Understanding the GitHub flow](https://guides.github.com/introduction/flow).

**Comment by mustafarabie** [comment]
> Hi @mustafarabie You have to create a fork of this repo under your account, and then push to your fork. From your fork, you'll then create a PR into this repo. Does that make sense? In your fork you'll create a feature branch, see [Understanding the GitHub flow](https://guides.github.com/introduction/flow).

Makes perfect sense. PR created. Thanks
