### ISSUE TITLE
Feature request: System.Text.Json (alternative to Newtonsoft)

### ISSUE THREAD

**Issue by Zettersten** [IEvangelist/azure-cosmos-dotnet-repository#133]
Not sure if lower dependencies can manage this request/feature but it’d be cool to see this AMAZING project support the newer System.Text.Json for deserialization/serialization and attributing (keys, partitions, etc).

perhaps even, a “bring your own serializer” solution. 

Either way - would be eager to hear your alls thoughts!

**Comment by IEvangelist** [comment]
Hi @Zettersten - this is something that we've thought about for sure. I believe that in the future, the official Cosmos DB .NET SDK will be porting to the new `System.Text.Json` serializer. I'm curious if they're going to expose some sort of "bring your own serializer" solution. Which I agree would be ideal. But we're a bit hands tied unfortunately. We cannot change it, unless they do as it's simply not expose to us.
