### ISSUE TITLE
add JsonStringEnumConverter for model

### ISSUE THREAD

**Issue by Krysztal** [IEvangelist/azure-cosmos-dotnet-repository#136]
I would like to save my enum name instead of value to database.  Could you add JsonStringEnumConverter support for storing?

**Comment by IEvangelist** [comment]
Hi 👋 @Krysztal 
Thank you so much for posting this issue. We really appreciate it. @mumby0168 is working on getting the docs site stood up for this repo, and from there we could work to add content around the existing JSON serialization support.

This is related to #105 in that we answered how to customize serialization there. Does that help?

**Comment by Krysztal** [comment]
Hi David, 
no really. Options what are at issue 105 help to change naming of stored properties, but I need to store enum using property name, not the value. To do it automaticly in .NET you can use JsonStringEnumConverter, but repository does not support it.

**Comment by IEvangelist** [comment]
> Hi David, no really. Options what are at issue 105 help to change naming of stored properties, but I need to store enum using property name, not the value. To do it automaticly in .NET you can use JsonStringEnumConverter, but repository does not support it.

Hi @Krysztal - Ah, yes. I stand corrected, you're right. @mumby0168 and I are looking at custom serialization bits. It might be related to this, but as of right now it's not supported.

**Comment by mumby0168** [comment]
Hi @Krysztal and @IEvangelist have you tried adding the attribute to the given properties? I know it's not ideal but that is how I have worked around it for the time being. It looks like this

```csharp
[JsonConverter(typeof(StringEnumConverter))] 
public MyEnumType MyType { get; set; }
```

**Comment by mumby0168** [comment]
@IEvangelist it might be nice to add support for system.text JSON serializers but to start with as an opt-in option that is configured on startup, we could then expose the full range of options that provides, this could be done by a simple implementation of the `CosmosSerializer` we have spoken of before

**Comment by Krumelur** [comment]
I tried @mumby0168 's suggestion of using `[JsonConverter(typeof(StringEnumConverter))]` but it still results in integers being stored. I just ported to code over from using Cosmos DB Client - works like charm there. So not sure why the serializer option would be ignored by the wrapper?

**Comment by mumby0168** [comment]
> I tried @mumby0168 's suggestion of using `[JsonConverter(typeof(StringEnumConverter))]` but it still results in integers being stored. I just ported to code over from using Cosmos DB Client - works like charm there. So not sure why the serializer option would be ignored by the wrapper?

Hi @Krumelur I use this quite often and seems to work without issue. have you made sure you are using Newtonsoft?

See an example here full qualified

```csharp
using Newtonsoft.Json;

[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public DemandStatus Status { get; private set; }
```

if you have a little sample you could share, I can assist further :)

**Comment by Krumelur** [comment]
Thanks @mumby0168 .

Originally, I had this when using Cosmos Client:

```
using System.Text.Json.Serialization;
using Newtonsoft.Json.Converters;

[JsonConverter(typeof(StringEnumConverter))]
public enum OfferingKind
{
	Unknown,
	New,
        Retry
}
```

This worked fine. Now you're saying to put the attribute on the property, which I also tried:

```
public class Offering : Item
{
	/// <summary>
	/// Defines what kind of offering this is.
	/// </summary>
	[JsonConverter(typeof(StringEnumConverter))]
        public OfferingKind Kind { get; set; } = OfferingKind.Unknown;
}
```

Doesn't work either. When creating an offering:

```
var contentRepo = host.Services.GetService<ContentStorageRepo>();
await contentRepo!.CreateOffering(new Offering { Id = "some test offering"});
```

I get:
```
{
    "kind": 0,
    "id": "some test offering",
    "type": "Offering",
    "_rid": "0t8VAIpqs70JAAAAAAAAAA==",
    "_self": "dbs/0t8VAA==/colls/0t8VAIpqs70=/docs/0t8VAIpqs70JAAAAAAAAAA==/",
    "_etag": "\"5c00e1e5-0000-0d00-0000-61bb11be0000\"",
    "_attachments": "attachments/",
    "_ts": 1639649726
}
```

**Comment by Krumelur** [comment]
Ha! Found it. Auto completion sometimes can be a nightmare. It suggested `using System.Text.Json.Serialization;` instead of `using Newtonsoft.Json;`, which was only the 2nd item to select. I just went "CTRL + . " and "ENTER". Sorry for the confusion. Now it's working.

**Comment by mumby0168** [comment]
> Ha! Found it. Auto completion sometimes can be a nightmare. It suggested `using System.Text.Json.Serialization;` instead of `using Newtonsoft.Json;`, which was only the 2nd item to select. I just went "CTRL + . " and "ENTER". Sorry for the confusion. Now it's working.

Okay great, this caught me out just the other day as well lol. Glad your sorted 👍

**Comment by IEvangelist** [comment]
> > Ha! Found it. Auto completion sometimes can be a nightmare. It suggested `using System.Text.Json.Serialization;` instead of `using Newtonsoft.Json;`, which was only the 2nd item to select. I just went "CTRL + . " and "ENTER". Sorry for the confusion. Now it's working.
> 
> Okay great, this caught me out just the other day as well lol. Glad your sorted 👍

So can we close this issue, or is there still something wrong?

**Comment by Krumelur** [comment]
I'm not the original poster, but my vote is to close it because putting `[JsonConverter(typeof(StringEnumConverter))]` on the property or even on the `enum` itself seems to be the standard solution to the problem.

**Comment by mumby0168** [comment]
@IEvangelist this is interesting related to the discussion we had about supporting `System.Text.Json` vs `Newtonsoft.Json` and exposing more of the features

**Comment by mumby0168** [comment]
Hi, @IEvangelist @Krumelur @Krysztal I am going to close this issue given we have had a resolution and no push back since.

Thanks all.
