### ISSUE TITLE
The ability to turn off camel casing for dictionary key serialization

### ISSUE THREAD

**Issue by boylec** [IEvangelist/azure-cosmos-dotnet-repository#144]
**Is your feature request related to a problem? Please describe.**
When I persist an object with a Dictionary<string, T> camel casing is applied to my dictionary keys when the object is stored in Cosmos. I'm unable to find a way to turn this off.

**Describe the solution you'd like**
I'd like to be able to turn off dictionary key camel casing as part of config the same way I can turn off property name camel casing.

**Describe alternatives you've considered**
Considered changing my data model to not use dictionaries but I feel that this shouldn't be necessary.

**Additional context**

**Comment by boylec** [comment]
I've found a way to make this happen.

Couple notes:
* Had to specify the following in my config.
```
"RepositoryOptions__SerializationOptions__PropertyNamingPolicy": "Default"
```
* Specifying this in my startup .AddCosmosRepository as follows did not actually do anything
```
options.SerializationOptions = new RepositorySerializationOptions()
{
    PropertyNamingPolicy = CosmosPropertyNamingPolicy.Default
};
```
* I personally then specify a [JsonProperty("...")] attribute on each of my cosmos models to explicitly name the properties with casing as I please but if I remove those attributes, camel casing seems to be applied to the properties which is unexpected to me.
 
Is it expected that the "Default" property naming policy only affects how my dictionary keys are serialized but not my actual properties? Does my project's JsonObjectSerializer DI registration somehow get merged with the Cosmos serialization options?

**Comment by IEvangelist** [comment]
I'm happy that you were able to get this to work with the config. @mumby0168 it does look like we have a bug as the `AddCosmosRepository` should have honored this, right?

**Comment by mumby0168** [comment]
> I'm happy that you were able to get this to work with the config. @mumby0168 it does look like we have a bug as the `AddCosmosRepository` should have honored this, right?

Yeah, @IEvangelist I think we expose to opt-in implementations of the `CosmosSerializer` one which supports the full settings for `Newtonsoft.Json` & one that support's the full options for `System.Text.Json` then we can expose the full set of options provided for each and let clients migrate over to them as they please.

On the note of this issue would have to check if the value of the constant used in code = `Default` if it does not then not sure it would honour it, what do you think?

**Comment by IEvangelist** [comment]
Yeah, I suppose that's a bit tricky. We should continue to monitor the potential abstractions from the Cosmos team for JSON serialization. Thanks

**Comment by boylec** [comment]
Update:

I've since found a better way to accomplish this without needing to specify [JsonProperty(...)] for each and every property in a collection/container.

Since Cosmos uses NewtonSoft / Json.NET under the cover implement a custom converter specifically for dictionaries that you don't want to enforce a naming strategy on:

```
public class VerbatimDictionaryConverter<TKey, TValue> : JsonConverter<IDictionary<TKey, TValue>>
    {
        [JsonDictionary(NamingStrategyType = typeof(DefaultNamingStrategy))]
        class VerbatimDictionarySerializationSurrogate : IReadOnlyDictionary<TKey, TValue>
        {
            readonly IDictionary<TKey, TValue> dictionary;

            public VerbatimDictionarySerializationSurrogate(IDictionary<TKey, TValue>? dictionary)
            {
                if (dictionary == null)
                    throw new ArgumentNullException(nameof(dictionary));
                this.dictionary = dictionary;
            }
            public bool ContainsKey(TKey key) { return dictionary.ContainsKey(key); }
            public bool TryGetValue(TKey key, out TValue value) { return dictionary.TryGetValue(key, out value); }
            public TValue this[TKey key] { get { return dictionary[key]; } }
            public IEnumerable<TKey> Keys { get { return dictionary.Keys; } }
            public IEnumerable<TValue> Values { get { return dictionary.Values; } }
            public int Count { get { return dictionary.Count; } }
            public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator() { return dictionary.GetEnumerator(); }
            IEnumerator IEnumerable.GetEnumerator() { return GetEnumerator(); }
        }

        public override void WriteJson(JsonWriter writer, IDictionary<TKey, TValue>? value, JsonSerializer serializer)
        {
            serializer.Serialize(writer, new VerbatimDictionarySerializationSurrogate(value));
        }

        public override bool CanRead { get { return false; } }

        public override IDictionary<TKey, TValue> ReadJson(JsonReader reader, Type objectType, IDictionary<TKey, TValue>? existingValue, bool hasExistingValue, JsonSerializer serializer) { throw new NotImplementedException(); }
    }
```

Then use the converter on the IDictionary-implementing property:

```
[JsonConverter(typeof(VerbatimDictionaryConverter<string, string>))]
public IDictionary<string, string>? Categories { get; set; }
```
