### ISSUE TITLE
JSON serialisation in the InMemoryRepository

### ISSUE THREAD

**Issue by robertbennett1998** [IEvangelist/azure-cosmos-dotnet-repository#145]
**Is your feature request related to a problem? Please describe.**
When using the InMemoryRepository for testing it is possible to write a test that would pass but the actual code been tested could cause JSON serialisation issues. This is because the InMemoryRepository doesn't serialise / deserialise the objects stored.

**Describe the solution you'd like**
The InMemoryRespository should serialise / deserialise as the actual repository would.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by mumby0168** [comment]
Hi @robertbennett1998 really like this idea, we could look at performing the serialization & deserialization as well as storing the concrete types, this would add an extra step getting closer to mimicking the real service 😃

**Comment by mumby0168** [comment]
Closed as part of #146 well done @robertbennett1998 thanks very much 😄
