### ISSUE TITLE
Functional/Integration Tests

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#164]
It would be good if we could look at adding some tests that run against the real cosmos DB service to assert that the functions we provide are working between PR's and commits to avoid releasing issues in the library.

I see a few options for this:

* Run the tests against a provisioned cosmos account in the cloud, we could utilize the free tier of 1000 RUs (Connection String as an environment variables in a GA)
* Run these tests against the simulator hosted via docker in a GitHub action

I think either option would have to delete the database after any tests and re-create it next. These could tie the library together using Microsoft's `IServiceProvider`.

Once this is set up we can write some tests that act like integration/functional tests of the library to confirm critical flows always work when the library is modified.

**Comment by ylr-research** [comment]
I like option 1

**Comment by ylr-research** [comment]
Never mind. Answer is above

**Comment by ylr-research** [comment]
@mumby0168 any specific account you prefer to use for testing?

**Comment by mumby0168** [comment]
> @mumby0168 any specific account you prefer to use for testing?

No, we'd have to chat to @IEvangelist around this I think, we'd not want to run these over & over depending on there RU consumption we would want to avoid this costing us if possible I think but they would provide a large benefit I think, but like with any functional tests we want this to be solid and repeatable and certainly not flakey which is something we would have to consider from the get go. Sure it's possible tho, going to have a look into this soon 😃

**Comment by dcuccia** [comment]
Can we ensure for a class of functional tests that only one instance runs concurrently? If not, we could run them against the real DB as a scheduled cron job (nightly or hourly), so that we're ensured to not go over the limit.

**Comment by mumby0168** [comment]
> Can we ensure for a class of functional tests that only one instance runs concurrently? If not, we could run them against the real DB as a scheduled cron job (nightly or hourly), so that we're ensured to not go over the limit.

We could look to do that if they get that big I think to start with we should be okay, they only need to be smoke tests really just to make sure the core bits of the library function properly, so should be okay to run on a PR I think maybe they have to manually run. We don't get that many PRs at the same time.

**Comment by mumby0168** [comment]
The basics of these are now in place, I want to add some contribution documentation to this. See the [Accepetance Tests here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/tree/main/tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests)

**Comment by mumby0168** [comment]
These are running as part of the CI build on main now. Going to close this issue.
