### ISSUE TITLE
Allow for sorting when doing paginated requests

### ISSUE THREAD

**Issue by filipmhpersson** [IEvangelist/azure-cosmos-dotnet-repository#165]
**Is your feature request related to a problem? Please describe.**

We need to be able to sort paginated queries. I see this as a critical feature needed for paging. Lists usually needs to be sorted and when the requests is paginated that the needs to be done serverside otherwise we always need to get all of the data, sort it and then page it, instead of letting the cosmos db serve the paginated response.

I'm not sure if I have missed something in the interface but apart from direct SQL queries I don't see a possibility to do sorting when using PageAsync. And if I understood correctly doing direct queries will ruin the possibility to use the in memory database for testing. Which is a really nice feature to have.

**Describe the solution you'd like**
The biggest question for this feature is how update the IRepository interface to include sorting. 

My suggestion would be to look at the specification pattern that can be seen here:

https://github.com/ardalis/Specification

But limit it to whats needed here, since the ardalis specification implementation is sql + EF specific. This would also allow for a scalable way to implement more features in the future. This is what I think would be needed for a specification pattern that's not too complex to implement and would give value right now:

 ```  c#
 //Setup classes
 public interface ISpecification<T>
    {
        IEnumerable<Expression<Func<T, bool>> WhereExpressions { get; }
        IEnumerable<Expression<Func<T, object?>>, OrderTypeEnum> OrderExpressions { get; }

        int? Take { get; }
        int? Skip { get; }

        string? ContinuationToken{ get; }
    }

  public enum OrderTypeEnum
    {
        OrderBy = 1,
        OrderByDescending = 2,
        ThenBy = 3,
        ThenByDescending = 4
    }
    
//Page method:

public async ValueTask<IPageQueryResult<TItem>> PageAsync(
            ISpecification<TItem>,
            CancellationToken cancellationToken = default)
 ```

**Describe alternatives you've considered**
It is also possible to extend the page method to include the order by clause:
`  IEnumerable<Expression<Func<T, object?>> ` 
But I don't think this is a scaleable way to keep developing the repository. It will probably lead to a method that just keeps growing in size. 

Another solution is to got the IQueryable path but I agree with the conclussions reached here: https://github.com/IEvangelist/azure-cosmos-dotnet-repository/issues/88 that opening the door to IQueryable will add lots of complexity for the small subset of features thats needed. 

**Additional context**
If there currently is another way to sort results for a paged query please let me know, I have tried to look everyone but then I missed it.

**Comment by mumby0168** [comment]
Hi @filipmhpersson this is something in the plans and we have discussed it briefly here what do you think to the proposal inside this issue? #88

It talks of a decorator to expose some extra functionality such as `.OrderBy` which I assume would suit the situation you are describing?

I will have a read of that specification pattern that is new to me but looks interesting, was this a feature suggestion you'd want to potentially contribute yourself?

**Comment by filipmhpersson** [comment]
I think it is a similar solution and probably up to taste more than anything else how it should be implemented. One of the things I like with the specification pattern is that it is used by dotnet-architectures samples (example https://github.com/dotnet-architecture/eShopOnWeb). Which makes it recognizable to many dotnet developers.

If we agree on how the api should look for sorting it is something I can help contribute to. We are interested in this project and this is the missing piece for us that we need to be able to replace other .net sdks for cosmos with this.

**Comment by mumby0168** [comment]
> I think it is a similar solution and probably up to taste more than anything else how it should be implemented. One of the things I like with the specification pattern is that it is used by dotnet-architectures samples (example https://github.com/dotnet-architecture/eShopOnWeb). Which makes it recognizable to many dotnet developers.
> 
> If we agree on how the api should look for sorting it is something I can help contribute to. We are interested in this project and this is the missing piece for us that we need to be able to replace other .net sdks for cosmos with this.

Okay that sounds great, I am happy for you to do to put up a PR and we can have a look? 

What was your plan of action? Was it to look at adding the specification pattern as an overload to each existing `PageAsync(...)` that we have or was it to add a new one with a different signature? Either way happy to review a PR sometimes seeing the code with a sample attached is the best way 😃

**Comment by filipmhpersson** [comment]
It really depends on if we should introduce breaking changes or not. But I think the best way would be to introduce it is an overloaded page method and then later on it's possible to deprecate other methods if they are not needed. 

But this is a big change on how we interact with queries to the repository and I feel that we at least need a bit more discussion to decide on how the interface should look before any coding is done.

**Comment by mumby0168** [comment]
> It really depends on if we should introduce breaking changes or not. But I think the best way would be to introduce it is an overloaded page method and then later on it's possible to deprecate other methods if they are not needed.
> 
> But this is a big change on how we interact with queries to the repository and I feel that we at least need a bit more discussion to decide on how the interface should look before any coding is done.

Okay yes, I would agree with avoiding breaking changes where possible, so I also prefer the overloaded method.

I have been looking into the specification pattern, I like the concept! In terms of the two different paging methods we currently implement one being the continuation token and the other being the basic skip take the approach, how would you see this shaping up as specifications? Would we have an interface for each version with specific properties so if someone wanted to use either method then their specification that they detail would inherit from the said interface? 

My other question would be as well is there a way to limit the operators used Cosmos DB only supports a limited set so it would also be nice to try and limit this? Even if for the first iteration we just support `.Where(...)` and `.OrderBy(...)` it would be nice to know the solution support's adding these without breaking changes, what do you think?

The last thing I would like to discuss is that we do have plans to wrap the page methods we already have inside something that returns `IAsyncEnumerable<IPage<T>>` this is still something I'd like to see although I don't see this specification pattern impacting this in any way I thought it was worth mentioning 😃

**Comment by filipmhpersson** [comment]
Hmm for different paging I think both methods are actually needed and serve different purposes. I think it's easiest to keep them in the same specification and use helpful messages and maybe even InvalidOperationException if someone tries to combine them. Or we say that continuation token is prioritized over skip/take.

Regarding the limited operations I would say the specification pattern will work exactly like the expression query works today in the repository. Meaning that a user can already send in a really weird function expression that cannot be evaluated by the cosmos SDK and will break. The good thing with the specification pattern here is that in the future easily add more operators without breaking any existing functionality. If you take my example here it's simple to and an Select expression without breaking any existing consumers. Then of course implementing select + orderby is complex but it's not something that we need to do right now :).

Did that answer you question or any other worry?

I agree with the last part I don't see any reason why a pattern for how to query would impact an IAsyncEnumerable  implementation.

**Comment by mumby0168** [comment]
Okay yes I think I like this as a concept @filipmhpersson did you say you fancied raising a PR for this?

**Comment by filipmhpersson** [comment]
If we agree on the interface I can raise a PR on it. But I can't really spend the time on a PR if we can't agree before the PR on what the general solution for sorting should be.

**Comment by IEvangelist** [comment]
I like it, one thing to alter is that the new APIs wouldn't need the `continuationToken` right?

You had:

```csharp
ValueTask<IPage<TItem>> PageAsync(
      ISpecification<TItem> specification,
      string continuationToken = null,
      CancellationToken cancellationToken = default);
```

But I think it would be:

```diff
ValueTask<IPage<TItem>> PageAsync(
      ISpecification<TItem> specification,
-     string continuationToken = null,
      CancellationToken cancellationToken = default);
```

**Comment by mumby0168** [comment]
> I like it, one thing to alter is that the new APIs wouldn't need the `continuationToken` right?
> 
> You had:
> 
> ```cs
> ValueTask<IPage<TItem>> PageAsync(
>       ISpecification<TItem> specification,
>       string continuationToken = null,
>       CancellationToken cancellationToken = default);
> ```
> 
> But I think it would be:
> 
> ```diff
> ValueTask<IPage<TItem>> PageAsync(
>       ISpecification<TItem> specification,
> -     string continuationToken = null,
>       CancellationToken cancellationToken = default);
> ```

It depends, I wanted to see the continuation token option obvious that you are using it by maybe keeping the separate would asssit?

**Comment by IEvangelist** [comment]
Yeah, let's see what the PR looks like and go from there. I'm good either way.

**Comment by filipmhpersson** [comment]
Ok I'll start looking at making PR for this

**Comment by mumby0168** [comment]
> Ok I'll start looking at making PR for this

Great! Feel free to raise a Draft PR at any time 😃  if you want some feedback.

**Comment by filipmhpersson** [comment]
Draft PR:
https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/171

Like I said in the PR description. 

My biggest hurdle right now is trying to get both pagination patterns to fit and work with the same Page return type. And I'm currently not sure how we can get current page when using continuation token.

Maybe it's something that has to be separated or do you think it's something that can be solved?

**Comment by mumby0168** [comment]
Great work @filipmhpersson this is now released 💪🏻
