### ISSUE TITLE
[New Feature] Adding query costs to debug logging to aid developer inner loop

### ISSUE THREAD

**Issue by WestDiscGolf** [IEvangelist/azure-cosmos-dotnet-repository#174]
**Is your feature request related to a problem? Please describe.**
Currently there is limited support to determine how many RUs are used for each query. This is currently only surfaced in the paging functionality.

**Describe the solution you'd like**
After discussions on twitter with @mumby0168 it was determined that we could add the costs to debug statements to allow for this to aid developers locally - https://twitter.com/billydev5/status/1482287510990426113

**Comment by mumby0168** [comment]
Thanks @WestDiscGolf for raising this I think you are right, it will really help people to get a feel of what their queries cost.
