### ISSUE TITLE
How to use if accessing multiple database in the same application?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [IEvangelist/azure-cosmos-dotnet-repository#19]

**Comment by IEvangelist** [comment]
Currently, it is only possible to work with a single database at a time with this SDK. However, you could work with multiple containers within the same database. Otherwise, you may want to consider using just the Cosmos DB .NET SDK - which this wraps.

**Comment by Ibrahim-Islam** [comment]
Why cant this be extended to support this use case?

**Comment by IEvangelist** [comment]
The configuration extensions currently limit this, it would take a lot of work to change the design of this SDK and corresponding API surface area.

I'd have to consider how to go about doing that, it might be something that I could consider for future work, and maybe it could follow a factory pattern where you registered named databases and get `IRepository<TItem>` instances that correspond to a named DB.

**Comment by anktsrkr** [comment]
Hey @IEvangelist  Could you please share some psudo code for what you think? That would really help and I guess it is very much necessary to support multiple databases from a application what I think.

**Comment by emrekara37** [comment]
Hi @IEvangelist  I want to contribute by implementing the multi-database feature, will you advise me?

**Comment by IEvangelist** [comment]
Hi @emrekara37 - sounds good. This would take a bit of work; I think we should start with a discussion first, that way others can more easily chime in. See https://github.com/IEvangelist/azure-cosmos-dotnet-repository/discussions/271
