### ISSUE TITLE
Enable nullable reference types

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#194]
The library could benefit from nullable reference types being enabled. This would aid internal development as well also let us properly decorate external APIs where they can return `null`.

**Comment by mumby0168** [comment]
@IEvangelist is there any guidance on this, seen a few bits when googling that suggest targeting a framework as well as `netstandard2.0` such `net6`. I'd seen you'd just done an MS learn module for this. I figured you'd be the best person to ask 😊

**Comment by IEvangelist** [comment]
Still working on the learn module, but I do agree that this could be helpful here. Let me think on this a bit more and get back to you.

**Comment by IEvangelist** [comment]
Yes, I think we should enable this. Nullable reference types were added in C# 8, and I thought we were using later versions than that already.

**Comment by mumby0168** [comment]
> Yes, I think we should enable this. Nullable reference types were added in C# 8, and I thought we were using later versions than that already.

Okay great stuff :)
