### ISSUE TITLE
Add configuration option to bypass calls to Create___IfNotExists()

### ISSUE THREAD

**Issue by cjbanna** [IEvangelist/azure-cosmos-dotnet-repository#218]
**Is your feature request related to a problem? Please describe.**
The `DefaultCosmosContainerService` calls both `CreateDatabaseIfNotExists()` and `CreateContainerIfNotExists()` during startup. While this implementation is acceptable for hosts with long running processes, such as hosting in IIS and Azure App Service, in Azure Functions it is executed on every function call. The result is an additional 50-60ms to calls that take only ~50ms. This essentially doubles the time it takes for every call to complete.

You can verify the results by creating a new CosmosDb database and executing some inserts. Then, replace the relevant lines in `GetContainerAsync()` with the following:

``` csharp
var database = await _cosmosClientProvider
    .UseClientAsync(client => Task.FromResult(client.GetDatabase(_options.DatabaseId)))
    .ConfigureAwait(false);

var container = database.GetContainer(containerId);
```

Yes, this is an edge case. And yes, one could easily provide their own implementation of `ICosmosContainerService` that does not call the `CreateIfNotExists()` method, but it'd be a lot cooler if you didn't have to go to all that trouble.

**Describe the solution you'd like**
Add a configuration option to `RepositoryOptions` that allows one to choose if they want the `CreateIfNotExists` behavior.

**Describe alternatives you've considered**
Creating a different implementation of `ICosmosContainerService` and registering that into the DI container instead of `DefaultCosmostContainerService`

**Comment by mumby0168** [comment]
Hey @cjbanna how are you using this in your functions? Are you using a functioning startup? As described here -> https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

Would you be able to share your `.AddCosmosRepository(options => ...)` for a little more context?

**Comment by cjbanna** [comment]
Thanks for the reply. I didn't follow the guidance in the project. After following the example in the Azure Functions project, it works as expected. Closing this issue.
