### ISSUE TITLE
Refactor `InMemoryRepository<TItem>` into `partial` classes

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#222]
The file that contains all of the in-memory implementations is getting quite large. It would be great to see this tidied up a little.

See the work that was done as part of this PR for inspiration ➡️ #221

**Comment by IEvangelist** [comment]
> Hi, can I try to fix this one ? thanks

Hi @idormenco, Yes. Please tag this issue in the PR. Thank you

**Comment by mumby0168** [comment]
Hi @IEvangelist @idormenco happy for you to help might be worth coordinating with @robertbennett1998 he started this PR #268 which may cover very similar ground, any ETA on this @robertbennett1998 ?
