### ISSUE TITLE
Issue loading Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by daveabrock** [IEvangelist/azure-cosmos-dotnet-repository#23]
I'm not sure if this is a problem with my machine or not, but wanted to ask.

When I try to run my Azure Function after bringing in and using your awesome library, I get a runtime error:

```
[2020-11-27T15:01:03.561Z] Api: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```

I've tried to mirror your sample, so my project file looks almost the same as yours. Here's the most important bits:

```xml
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
...
<ItemGroup>
    <PackageReference Include="IEvangelist.Azure.CosmosRepository" Version="2.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.10" />
</ItemGroup>
```
The difference is that I fetched your project in NuGet, and in your sample you're using a project reference. When I look at dependencies in NuGet, I see it is supported in .NET Standard 2.0:

![image](https://user-images.githubusercontent.com/275862/100462633-263eb600-3090-11eb-8229-68b91b54f7e9.png)

I'm using .NET Core 3.1, as you are, so that should be OK. Knowing the `Microsoft.Azure.Cosmos` dependency wasn't an issue, I explicitly referenced the `Microsoft.Extensions.*` dependencies in my project file but that didn't help.

I noticed a GitHub issue from a few weeks ago, noting a potential problem [with the host version](https://github.com/Azure/azure-functions-host/issues/6893). Are these `5.0.0` dependencies mucking things up?

**Comment by IEvangelist** [comment]
Hi @daveabrock - thank you so much for posting this issue. I have not actually created an Azure Function yet, using the recent updates from @Invvard. I'm curious if this isn't an issue that is related to .NET 5, I'll have to try this and get back to you. With that said, I'm curious if @Invvard has used this SDK with their updates to try out Azure Functions yet? Maybe they have some insights?

**Comment by daveabrock** [comment]
I believe I figured out the issue. I cloned the repo, and added it to my project. I was able to reproduce the runtime error and to resolve it by reverting `Microsoft.Extensions.Options.ConfigurationExtensions` down to 3.1.10:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.14.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.10" />
    <PackageReference Include="MinVer" Version="2.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
``` 

I was going to submit a PR (and I can, if you want) but I would imagine you would want to make sure it doesn't break anything else—it shouldn't (and your tests pass!), but you know what they say about assuming. 😎

**Comment by IEvangelist** [comment]
PRs are absolutely encouraged and celebrated, by all means - please feel free to submit one. I'd be happy to review it. So, is there an issue with the code - and can we close this?

**Comment by IEvangelist** [comment]
The version with these fixes is now live on NuGet:
https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository/2.1.2
