### ISSUE TITLE
Support for QueryDefinition 

### ISSUE THREAD

**Issue by afacanerman** [IEvangelist/azure-cosmos-dotnet-repository#27]
Hi, 

`GetByQueryAsync` is accepting only string type query. This is open to the SQL injection attacks. Would it be ok to create another overload that accepts CosmosDB `QueryDefinition`?

`ValueTask<IEnumerable<TItem>> GetByQueryAsync(QueryDefinition queryDefinition, CancellationToken cancellationToken = default);`

I think this change would introduce CosmosDB package to the client but it would be safer.

I could create a PR if you want me to.

**Comment by IEvangelist** [comment]
Ultimately, this calls into the official Azure Cosmos DB .NET SDK instantiating a `QueryDefinition` itself from the `string` representation of the query. It is just as vulnerable to injection as exposing an overload with the `QueryDefinition` as they are both based on a raw `string`.

[See here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs#L112). They official SDK requires a `QueryDefinition` already, but I suppose adding it would then allow consumers to use the fluent [`.WithParameter`](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c80802016c5a752153b599d08650d6e824b9b6b1/Microsoft.Azure.Cosmos/src/Query/v3Query/QueryDefinition.cs#L84) chaining method. I would accept a PR that adds this.

**Comment by afacanerman** [comment]
The PR created. Thank you

**Comment by IEvangelist** [comment]
Fixed in #29
