### ISSUE TITLE
use System.Text.Json as the Json serializer

### ISSUE THREAD

**Issue by SeanFarrow** [IEvangelist/azure-cosmos-dotnet-repository#273]
I really like this project.

We are starting to use this in a new .Net 6-based Azure functions project.

I noticed that NewtonSoft.Json was used for the serialization.

Would it be possible to move to using System.Text.Json?

I'm happy to do the work, if that would help.
Thanks,
Sean.

**Comment by IEvangelist** [comment]
We are currently stuck with NewtonSoft.Json as that is what the underlying official .NET SDK for Cosmos DB uses. I believe that there is an effort to allow for a bring your own serializer option coming, but I do not know when.

**Comment by SeanFarrow** [comment]
Ok, makes sense.
The hacks seem a bit nasty.
Let’s close this and I’ll re-open when v4 comes out.
Thanks,
Sean.

**Comment by VaticanUK** [comment]
You can use a different serializer now (unsure when it became available) by inheriting from CosmosSerializer

```
public class CosmosSystemTextJsonSerializer : CosmosSerializer
{
    public override T FromStream<T>(Stream stream)
    {
        return stream.FromJson<T>() ?? default!;
    }

    public override Stream ToStream<T>(T input)
    {
        return input.ToJsonStream();
    }
}
```

and then referencing in CosmosClientOptions:

```
new CosmosClientOptions
{
    Serializer = new CosmosSystemTextJsonSerializer()
}
```

**Comment by eholman** [comment]
The System.Text.Json serializer option works great!

The only thing is... while setting the serializer on the CosmosClientOptions, the `AddInMemoryCosmosRepository()` is still using Json.NET.

This leads to different serializing behaviour in e.g. writing tests and running the application.

**Comment by IEvangelist** [comment]
That's an excellent observation. Would any of you be interested in working on addressing this issue?

**Comment by SeanFarrow** [comment]
@IEvangelist  yes, what's the timescale for the next release?

**Comment by eholman** [comment]
I can also work on it. There is also another challenge, in combination with Serializer instead of SerializerOptions and Casing Strategy.

**Comment by IEvangelist** [comment]
No, immediate release timescale. Take your time, and this is much appreciated. Thank you.

**Comment by sven5** [comment]
I'm running into this issue. When using custom `CosmosSerializer` the naming convention for `type` property of the underlying query doesn't get applied. Is there any solution?

**Comment by IEvangelist** [comment]
Hi @sven5 - Sorry you're experiencing issues.

> I'm running into this issue. When using custom `CosmosSerializer` the naming convention for `type` property of the underlying query doesn't get applied. Is there any solution?
> 
> to be more precise, the query gets generated with `Type` instead of `type` `((NOT IS_DEFINED(root[\"Type\"])) OR (root[\"Type\"] = \"Product\")))"`

What does your repository configuration look like? Are you using something like:

```json
"RepositoryOptions": {
  "CosmosConnectionString": "<CosmosDB-ConnectionString>",
  "DatabaseId": "<CosmosDB-DatabaseName>",
  "ContainerId": "<CosmosDB-ContainerName>",
  "SerializationOptions": {
    "PropertyNamingPolicy": "CamelCase"
  }
}
```

Notice the `SerializationOptions` section. Also, what version are you on?

**Comment by SeanFarrow** [comment]
This is something I plan to look at in a couple of weeks—probably by the end of October.

**Comment by IEvangelist** [comment]
I just made an update, see 0788386c1d47cd1ac3e90a6d6ac6e3559db2c63f. This added an implicit operator for the `RepositorySerializationOptions` that maps to the `CosmosLinqSerializerOptions`. I now flow that through all the `GetItemLinqQueryable` calls. That might be the fix.

**Comment by sven5** [comment]
@IEvangelist that would be great. 👍

**Comment by IEvangelist** [comment]
This issue is out of scope, since we can't control the serializer (yet). If that changes in the future, we can revaluate this... but for now, let's close this. And @sven5 - see https://github.com/IEvangelist/azure-cosmos-dotnet-repository/releases/tag/7.1.0.

**Comment by sven5** [comment]
@IEvangelist Thanks for you update. Now it's working perfectly.

**Comment by sven5** [comment]
@IEvangelist  just one question, do you know when the CosmosDB team is planning to step over to `System.Text.Json`?   Is there even any schedule?
