### ISSUE TITLE
Allow a user to change the type used for the IItemWithTimestamps interface

### ISSUE THREAD

**Issue by SeanFarrow** [IEvangelist/azure-cosmos-dotnet-repository#276]
I currently use Nodatime to do all my date/time work.

It would be nice if the IItemWithTimestamps interface was generic so I could directly use this without going through a conversion

**Comment by mumby0168** [comment]
Hi @SeanFarrow `IItemWithTimestamps` is just our custom extension on the initial `IItem` I am sure you could create your own version which uses `Nodatime`. It's not something I have used before.

**Comment by SeanFarrow** [comment]
OK, that makes complete sense, thanks.
