### ISSUE TITLE
Support IAsyncEnumerable in the repositoy implementations

### ISSUE THREAD

**Issue by SeanFarrow** [IEvangelist/azure-cosmos-dotnet-repository#278]
Hi,

What is the roadmap for supporting the IAsyncEnumerable interface in the read methods of the IRepository interface?

If this isn't planned, it is something I'd be happy to work on.

**Comment by mumby0168** [comment]
Hi @SeanFarrow this has been planned for the paging methods. Not something we've had time to work on yet. I did wrap this myself in an implementation here. This was build on top of the paging support that already exists. However there is no reason this wrapper cannot be generic and provided by the library:

https://github.com/mumby0168/Nomad.Sorter/blob/88ff11adaf2efd85bd23fd235cad1f9a1e9b0573/src/Nomad.Sorter.Infrastructure/Data/Repositories/ParcelRepository.cs#L108-L139

**Comment by IEvangelist** [comment]
This seems related to #197

**Comment by SeanFarrow** [comment]
It is related, but should probably be done separately.
