### ISSUE TITLE
Support FirstOrDefaultAsync()

### ISSUE THREAD

**Issue by evancjohnson** [IEvangelist/azure-cosmos-dotnet-repository#280]
**Is your feature request related to a problem? Please describe.**
I've recently transitioned to this from my own CosmosDbRepository and I have noticed the method FirstOrDefaultAsync() does not exist in the context of this library. I was wondering if anyone had run into this or was planning on implementing it anytime soon.

**Describe the solution you'd like**
I would like if the `Microsoft.Azure.CosmosRepository.Extensions` was extended to include FirstDefaultAsync()

**Describe alternatives you've considered**
Currently I am calling ToListAsync() and then in a following line using first or default.

**Additional context**
I can implement this; I was unsure of your policies on help from others.

**Comment by IEvangelist** [comment]
Hi @evancjohnson,

We are thrilled to have external contributors provide features, and suggestions - as you've done here. When you write a PR, please reference this issue number and tag me for review.

**Comment by PaulOst** [comment]
Hi @evancjohnson! Did you ever submit a pull request for FirstOrDefaultAsync()?

**Comment by evancjohnson** [comment]
@PaulOst I just opened a PR for that an a few additional methods!

**Comment by PaulOst** [comment]
You're the best, @evancjohnson !

**Comment by mumby0168** [comment]
Thanks @evancjohnson see this release, it includes these changes:

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/releases/tag/3.6.0
