### ISSUE TITLE
Possibility to set Id property order

### ISSUE THREAD

**Issue by oleksandrkyselov** [IEvangelist/azure-cosmos-dotnet-repository#304]
I'm currently using an entity that inherits from FullItem, when I persist items at CosmosDB, I see the property id is at the bottom of the object structure.

It would be great to have the possiblity to set the order of a specific property / properties.

I've tried the following approach without luck:

```csharp
  public class Property : FullItem
    {
        [JsonProperty(Order = 1)]
        public new string Id { get; set; } = Guid.NewGuid().ToString();
     }
```

Is there any way to override or configure the order of the properties?

**Comment by IEvangelist** [comment]
I'm curious, why would the order matter for JSON serialization? Typically, the order is only relevant with binary serialization.

**Comment by alexkyse1** [comment]
Good question, when you persist data in Cosmos DB, you can explore it at Cosmos Explorer, whenever you want to check consistency between objects, do SQL queries in there, compare data to build your logic such as in power BI, you appreciate to have the essential identifier keys in top for you to be more agile in querying, joining and exploring your own data.

**Comment by IEvangelist** [comment]
I'm going to close this, as it's not something that is important enough to justify working towards. We can always revisit it, if there is enough interest later. Otherwise, feel free to write some tests and include the proposed changes to support this in a PR for consideration. Thanks for understanding.
