### ISSUE TITLE
Retrieve items Count based on GroupBy

### ISSUE THREAD

**Issue by rakeshrkumar6** [IEvangelist/azure-cosmos-dotnet-repository#310]
I am trying to retrieve items count based on group by. Could you suggest please how can I achieve that?  Below is my query

var groupByCountDtos = await _notificationRepository
               .GetByQueryAsync($"SELECT COUNT(1) AS Count, noti.NotificationType AS GroupByName FROM noti WHERE noti.UserUUId='{query.UUId}'" +
              $"AND noti.Status = {(int)NotificationStatus.UnRead} GROUP BY noti.NotificationType");

**Comment by IEvangelist** [comment]
Hi @rakeshrkumar6 - this seems to be an issue with how the query is constructed, and not our library. See: https://learn.microsoft.com/azure/cosmos-db/nosql/query/group-by. We simply pass the query through to the underlying official Cosmos DB .NET SDK APIs, thus, this issue wouldn't be related to our library. Does that make sense? I'm going to close this for now, but we can continue to discuss it if need be here.

**Comment by rakeshrkumar6** [comment]
@IEvangelist Could you please suggest, Can I use group-by query with this library. If yes!, could you share any example.

**Comment by IEvangelist** [comment]
I'd imagine you'd want to do something like this:

```csharp
var groupByCountDtos = await _notificationRepository
    .GetByQueryAsync($"""
        SELECT COUNT(1) AS Count, n.NotificationType AS GroupByName 
        FROM n
        WHERE n.UserUUId='{query.UUId}' 
        AND n.Status = {(int)NotificationStatus.UnRead} GROUP BY n.NotificationType
        """);
```

If you open your Azure Cosmos DB table explorer in the Azure portal, you can test our your queries there. Anything that you can do in there, can be replicated through this API. Also, try to correctly parameterize arguments instead of doing string interpolation.

**Comment by rakeshrkumar6** [comment]
@IEvangelist Thanks! for your quick response. 

But still I am not able to run this group by query. It is working fine when I am executing in Azure portal(as shown in below screen shot). 

![image](https://user-images.githubusercontent.com/69622464/224099008-9cd3147b-7e47-4af7-b699-3cc8f764dbe0.png)

When I am executing via code, it is not responding any results. 

```
 string groupByQuery = $"SELECT COUNT(1) AS Count, n.NotificationType AS GroupByName FROM n WHERE n.UserUUId='{query.UUId}' AND n.Status = {(int)NotificationStatus.UnRead} GROUP BY n.NotificationType";

            var groupByCountDtos = await _notificationRepository
    .                           GetByQueryAsync(groupByQuery);
```

Could you please suggest. Am i missing anything here?

**Comment by IEvangelist** [comment]
Ah, ok. So it returns an object array of items with `Count` and `GroupByName` values, is that the object type you're expecting?

**Comment by rakeshrkumar6** [comment]
@IEvangelist Yes! That's correct, I am expecting the same `Count` and `GroupByName` values.

**Comment by IEvangelist** [comment]
Sorry, been a bit buried - the `IRepository<TItem>` is only capable of returning items that are subclasses of `IItem`. You'd have to have the appropriate model and get an `IRepository<YourCountAndNameItem>` to resolve that query.

**Comment by IEvangelist** [comment]
I'm thinking this isn't supported then, I'm sorry. :(
