### ISSUE TITLE
Ignore null property for timeToLive when serialising

### ISSUE THREAD

**Issue by philip-reed** [IEvangelist/azure-cosmos-dotnet-repository#314]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.CosmosRepository).

**Describe the bug**
The TimeToLive wrapping property on `FullItem` should be ignored if null when serialising to avoid confusion when reading the raw json (as a human). It looks like a typo when the real `ttl` property is ignored when null, and could be misleading.

**To Reproduce**
Set a `null` value for `TimeToLive` on a `FullItem` and note that `"TimeToLive": null`, while `ttl` is not present.

**Expected behavior**
The `TimeToLive` wrapping property should also have a `[JsonProperty("timeToLive", NullValueHandling = NullValueHandling.Ignore)]` to match the `ttl` property.

**Actual behavior**
![image](https://user-images.githubusercontent.com/7798175/210549782-fb12f679-1326-4b65-b994-f6b64bef379e.png)

**Environment summary**
SDK Version: 7.0.0.0

**Additional context**
None

**Comment by philip-reed** [comment]
Looks like this is happening on the `EventItem` also.
I'm not sure if the `TimeToLive` property should be ignored when null, or ignored altogether?

**Comment by IEvangelist** [comment]
Closed by #315
