### ISSUE TITLE
Support for dedicated gateway with integrated cache

### ISSUE THREAD

**Issue by karpikpl** [IEvangelist/azure-cosmos-dotnet-repository#319]
**Is your feature request related to a problem? Please describe.**
I'm using dedicated gateway with [integrated cache](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-configure-integrated-cache). In order to increase cache hits, operations need to provide `MaxIntegratedCacheStaleness`.

**Describe the solution you'd like**
Ideally, there would be an override that takes `RequestOptions`, in order to provide `MaxIntegratedCacheStaleness`.
To be honest I'm not sure what's the best way of implementing this.

**Describe alternatives you've considered**
I've been trying to set this globally for the client, but I don't see this option.

**Additional context**
Here's the code snippet from Azure docs:
```csharp
FeedIterator<MyClass> myQuery = container.GetItemQueryIterator<MyClass>(new QueryDefinition("SELECT * FROM c"), requestOptions: new QueryRequestOptions
        {
            DedicatedGatewayRequestOptions = new DedicatedGatewayRequestOptions 
            { 
                MaxIntegratedCacheStaleness = TimeSpan.FromMinutes(30) 
            }
        }
);
```

**Comment by IEvangelist** [comment]
Hi @karpikpl - thanks for posting this issue. However, it seems like you're asking for an override to a method that we do not control. This repo is the unofficial wrapper around the official Azure Cosmos DB .NET SDK. The primary API exposed in this repo is the `IRepository<TItem>`, we abstract away the container to expose the repository-pattern.

**Comment by karpikpl** [comment]
ok, thanks @IEvangelist, this makes sense. There's only so much you can support with`IRepository<TItem>`
