### ISSUE TITLE
TryGetAsync using InMemoryCosmosRepository won't return the correct document

### ISSUE THREAD

**Issue by khingda-next** [IEvangelist/azure-cosmos-dotnet-repository#327]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.CosmosRepository).

**Describe the bug**
TryGetAsync won't return the cosmos document when using InMemoryCosmosRepository with item Type property set to a custom value.

**To Reproduce**
I'm using the below cosmos item class. 

```
internal class PersonDocument: FullItem
{
    public string PartitionKey { get; init; }  

    public PersonDocument(string id, string partitionKey)
    {
        Id = id;
        PartitionKey= partitionKey;
        Type = "Person";
        CreatedTimeUtc = DateTime.UtcNow;
    }

    protected override string GetPartitionKeyValue() => PartitionKey;
}

```

I have created PersonDocument as below: 
`var personA = new PersonDocument("A", "A");`

Create a person in cosmos using CreateAsync
`cosmosRepository.CreateAsync(personA );
`

read the newly created person using TryGeyAsync
`cosmosRepository.TryGetAsync(id: "A", partitionKeyValue: "A");`

**Expected behavior**
I would expect TryGetAsync to return the newly created PersonDocument. 

**Actual behavior**
It returns null. 

If I unset the type property on PersonDocument (as below) then it would return the PersonDocument as expected. 

```
internal class PersonDocument: FullItem
{
    public string PartitionKey { get; init; }
    
    public PersonDocument(string id, string partitionKey)
    {
        Id = id;
        PartitionKey= partitionKey;
        //Type = "Person";
        CreatedTimeUtc = DateTime.UtcNow;
    }

    protected override string GetPartitionKeyValue() => PartitionKey;
}
```

**Environment summary**
SDK Version: 7.0.1

**Comment by mumby0168** [comment]
Hi @khingda-next thanks for the issue, so this example is standard behaviour of the strongly typed nature of the library.

The reason for this being there is a container can share multiple types and we as a library provider always want to make sure that we get the correct type from that container. This is why we perform a check on the type name of the object against the type field stored on the document.

Currently there is an option to disable this type checking, as seen in the code snippet below:

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/f5e0cde4b410627d41d80606af058a2b2dd7ea7e/src/Microsoft.Azure.CosmosRepository/Providers/DefaultRepositoryExpressionProvider.cs#L24

`RepostioryOptions__UseStrictTypeChecking` set to false should do what you are after.

My only question would be why you choose to override the type name in this example?

**Comment by khingda-next** [comment]
Hi @mumby0168, thanks for you reply. I just wanted the cosmos item type to be different than the type name of the object. For the example above, if I don't set the type, it will be default "PersonDocument" whereas I would like it to be "Person".
