### ISSUE TITLE
No support for different type of items in TransactionalBatch

### ISSUE THREAD

**Issue by susal1** [IEvangelist/azure-cosmos-dotnet-repository#328]
https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/src/Microsoft.Azure.CosmosRepository/Repositories/DefaultRepository.Batch.cs

We are planning have a batch transaction with different items. The library at present only accept items of single type. Would there be any support for batch with different type of items ?

Thanks

**Comment by mumby0168** [comment]
Hi @susal1 we have an open issue that refers to this already, there is a fair bit of discussion on the topic. The basic batch support we have at the moment only supports documents of the same type.

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/issues/151

Open to any contributions and happy to help if needs be.
