### ISSUE TITLE
No In-memory implementation for ContinuationTokenSpecification 

### ISSUE THREAD

**Issue by khingda-next** [IEvangelist/azure-cosmos-dotnet-repository#329]
### Using ContinuationTokenSpecification on InMemoryRepository throws NotImplemented exception.

We have been using InMemoryRepositories for unit testing the repository calls. It recently came to our notice when we were using ContinuationTokenSpecification that it does not have in-memory implementation yet. 

```
if (specification.UseContinuationToken)
{
    throw new NotImplementedException();
}
```

Are we looking to add this feature any soon and if there are any alternatives please? Thanks!

**Comment by mumby0168** [comment]
Hi @khingda-next I would advise setting up a test instance of Cosmos DB either in the cloud or running as the emulator, the intricacies of the implementation of continuation tokens in our opinion could not be replicated well enough in the in memory store hence the reason we chose to just throw a not implemented exception here.

You can either require the emulator running on your machine, run it in docker or point your tests at a cloud instance see these docs:

https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21

**Comment by khingda-next** [comment]
Thanks for your response!
