### ISSUE TITLE
Repository that does not depend on the Item class

### ISSUE THREAD

**Issue by drma-dev** [IEvangelist/azure-cosmos-dotnet-repository#33]
![image](https://user-images.githubusercontent.com/12803050/103096657-66d41580-45e3-11eb-929e-44f95a6d13d8.png)

I'm new to the world of Cosmos DB, but I was thinking: If I make a custom query, which involves several containers, shouldn't my repository be free? Not being forced to inherit a class that defines the container?

**Comment by dcuccia** [comment]
@drma-dev you might be interested in [this merged PR](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/36), which allows custom entities that implement a new [IItem](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/IItem.cs) interface. Sample usage [here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/test/DefaultRepositoryFactoryTests.cs).

**Comment by IEvangelist** [comment]
This has since been released and is now in version 2.1.4, enjoy!

https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository/2.1.4
