### ISSUE TITLE
BadRequest (400) with Substatus 1001 when adding new item in Azure Cosmos DB using Microsoft.Azure.CosmosRepository library

### ISSUE THREAD

**Issue by rakeshrkumar6** [IEvangelist/azure-cosmos-dotnet-repository#331]
I getting an issue while creating a new item with CreateAsync method in Azure Cosmos DB using the Microsoft.Azure.CosmosRepository(https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository) library 7.0.1 version with .NET 6 Web Api application. I am receiving a BadRequest (400) response with Substatus 1001.

Here are the details:

I have a method AddEmailTemplate that updates an email template in the repository. However, when I execute the update operation, I receive the following error:

> Cosmos query executed for item type EmailTemplate with a charge of 2.8 RUs Query: {"query":"SELECT VALUE root FROM root WHERE ((((root["NotificationType"] = 3) AND (root["NotificationSubType"] = "")) AND (root["Language"] = "en-US")) AND ((NOT IS_DEFINED(root["Type"])) OR (root["Type"] = "EmailTemplate")))"} fail: SFH.N3.WebApi.Controllers.EmailTemplates.EmailTemplateController[0] An error occurred while updating email template, RequestId:338bcaa9-f8a3-418b-932b-4d88a7ab6a08 Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 1001; ActivityId: 5242793b-f785-436d-9565-5d7c1e730ef4; Reason: (); at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode() at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func2 createResponse) at Microsoft.Azure.Cosmos.ContainerCore.CreateItemAsync[T](T item, ITrace trace, Nullable1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken) at Microsoft.Azure.Cosmos.ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func2 task, Func2 openTelemetry, String operationName, RequestOptions requestOptions) at Microsoft.Azure.Cosmos.ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, String containerName, String databaseName, OperationType operationType, RequestOptions requestOptions, Func2 task, Func2 openTelemetry, TraceComponent traceComponent, TraceLevel traceLevel) at Microsoft.Azure.CosmosRepository.DefaultRepository`1.CreateAsync(TItem value, CancellationToken cancellationToken)

```
private async Task AddEmailTemplate(AddEmailTemplateCommand command)
        {
            var emailTemplateExist = await _repository
                .GetAsync(x => x.NotificationType == command.NotificationType
                && x.NotificationSubType == command.NotificationSubType
                && x.Language == command.Language).FirstOrDefaultAsync();

            // Insert email template
            if (emailTemplateExist == null)
            {
                var emailTemplate = new EmailTemplate
                {
                    Id = Guid.NewGuid().ToString(),
                    NotificationType = command.NotificationType,
                    NotificationSubType = command.NotificationSubType,
                    EmailSubject = command.EmailSubject,
                    Language = command.Language,
                    TemplateId = command.TemplateId,
                };
                await _repository.CreateAsync(emailTemplate);
            }
            else
            {
                string message = $"Email template already exists for the specified notification type:{command.NotificationType}";
                _logger.LogWarning(message);
                throw new EmailTemplateAlreadyExistsException(message);
            }
        }
```

EmailTemplate class:

```
[Container(nameof(EmailTemplate))]
    [PartitionKeyPath("/NotificationType")]
    public class EmailTemplate : Item
    {
       
        [JsonProperty(PropertyName = "NotificationType")]
        public int NotificationType { get; set; }

        [JsonProperty(PropertyName = "NotificationSubType")]
        public string NotificationSubType { get; set; }

        [JsonProperty(PropertyName = "Language")]
        public string Language { get; set; }

        [JsonProperty(PropertyName = "TemplateId")]
        public string TemplateId { get; set; }

        [JsonProperty(PropertyName = "EmailSubject")]
        public string EmailSubject { get; set; }

        protected override string GetPartitionKeyValue() => NotificationType.ToString();
       
        [JsonProperty(PropertyName = "_ts")]
        public long Timestamp { get; set; }
       
        [JsonIgnore]
        public DateTime TimestampAsDateTime => DateTimeOffset.FromUnixTimeSeconds(Timestamp).DateTime;
    }
```
appsettings.json

```
"RepositoryOptions": {
    "CosmosConnectionString": "AccountEndpoint={CosmosDbConnectionString}",
    "DatabaseId": "TestDb",
    "OptimizeBandwidth": true,
    "ContainerPerItemType": true,
    "AllowBulkExecution": true,
    "SerializationOptions": {
      "IgnoreNullValues": true,
      "PropertyNamingPolicy": "Default"
    }
  }
```

Cosmos Db Container:

![image](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/assets/69622464/365c76f5-3525-4de7-8be3-539b1905dc42)

I would appreciate any insights or suggestions on how to resolve this issue. Is there any specific meaning for Substatus 1001 in this context? How can I further investigate and resolve this error?

But `GetAsync` method is working fine, when I am retrieving the existing records(`var emailTemplates = await _repository.GetAsync(lambda)`;

**Comment by rakeshrkumar6** [comment]
> Only use `FirstOrDefaultAsync` if/when you know there is only one. Remove that and try getting the entire list back. Does that work, if so, you need better filtering in your lambda expression.

I apologize if my previous explanation was unclear. I want to clarify that the issue I'm facing is specifically related to the 'CreateAsync' method, while the 'GetAsync' method is working fine

**Comment by IEvangelist** [comment]
Oh, so the `CreateAsync` is failing? It's interesting as the `query` mentioned in the error log shows a `SELECT` not a `CREATE`. Did you setup everything correctly, as mentioned here: https://ievangelist.github.io/azure-cosmos-dotnet-repository/#advanced-partitioning-strategy

**Comment by rakeshrkumar6** [comment]
> Oh, so the `CreateAsync` is failing? It's interesting as the `query` mentioned in the error log shows a `SELECT` not a `CREATE`. Did you setup everything correctly, as mentioned here: https://ievangelist.github.io/azure-cosmos-dotnet-repository/#advanced-partitioning-strategy

@IEvangelist  Yes! I cross verified the container's partition key definition, it is correctly specified and also properly being send as Partition Key. I also updated my question and added my cosmos Db container with partition key value. This is very weird issue and not sure why it is not allowing me to add new item.

**Comment by rakeshrkumar6** [comment]
@IEvangelist One more thing I noticed, As `NotificationType` is my partition key field, and it is integer data type, but when I changed this field data type from `int` to `string` it starts working and I am able to insert new item with `CreateAsync` method. So is it mean we cannot use integer data type for partition with this library?

**Comment by IEvangelist** [comment]
> @IEvangelist One more thing I noticed, As `NotificationType` is my partition key field, and it is integer data type, but when I changed this field data type from `int` to `string` it starts working and I am able to insert new item with `CreateAsync` method. So is it mean we cannot use integer data type for partition with this library?

This sounds like a bug, where the `enum` isn't being serialized with the appropriate settings. You can customize the serialization options to control that - but you shouldn't have to. It should, just work... Thanks for bringing this to my attention, I'm not sure the best course of action.

The `string` type is the only type that I've used in the past as a partition key value as it works well as a synthetic (or composite), the fact that you're just using an `enum` implies that you're trying to partition on a likely tiny set of differences, which doesn't really make sense. You might consider not doing any custom partitioning at all if that is the case. What was the reasoning for partitioning on this member, what perceived advantages were you expecting?

**Comment by rakeshrkumar6** [comment]
> > @IEvangelist One more thing I noticed, As `NotificationType` is my partition key field, and it is integer data type, but when I changed this field data type from `int` to `string` it starts working and I am able to insert new item with `CreateAsync` method. So is it mean we cannot use integer data type for partition with this library?
> 
> This sounds like a bug, where the `enum` isn't being serialized with the appropriate settings. You can customize the serialization options to control that - but you shouldn't have to. It should, just work... Thanks for bringing this to my attention, I'm not sure the best course of action.
> 
> The `string` type is the only type that I've used in the past as a partition key value as it works well as a synthetic (or composite), the fact that you're just using an `enum` implies that you're trying to partition on a likely tiny set of differences, which doesn't really make sense. You might consider not doing any custom partitioning at all if that is the case. What was the reasoning for partitioning on this member, what perceived advantages were you expecting?

@IEvangelist  Previously, we were using the Cosmos DB SDK when we created the `EmailTemplate` container with `NotificationType` as the partition key. Recently, we have transitioned to a this library for performing CRUD operations on our containers in Cosmos DB. However, it appears that we cannot proceed with changing the data type of the partition key for the `EmailTemplate` container since it is already defined as an integer type. .

**Comment by IEvangelist** [comment]
I ran this in .NET Fiddle, and I see what you're saying now. The partition key is a `string` type, and that is by design. I never assumed that we would need a value other than `string`, again because it is very common practice to use synthetic or composite keys.

```cs
using System;
using Newtonsoft.Json;

var test = new EmailTemplate
{
    NotificationType = 7,
	NotificationSubType = "some sub type",
	Language = "en-US",
	TemplateId = Guid.NewGuid().ToString(),
	EmailSubject = "Hello world!",
	Timestamp = DateTime.Now.Ticks
};

// https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L40
var settings =  new JsonSerializerSettings()
{
	NullValueHandling = NullValueHandling.Ignore,
	Formatting = Formatting.Indented,
	MaxDepth = 64, // https://github.com/advisories/GHSA-5crp-9r3c-p9vr
}; 
var json = JsonConvert.SerializeObject(test, settings);
Console.WriteLine(json);

public class EmailTemplate
{
	[JsonProperty(PropertyName = "NotificationType")]
	public int NotificationType { get; set; }

	[JsonProperty(PropertyName = "NotificationSubType")]
	public string NotificationSubType { get; set; }

	[JsonProperty(PropertyName = "Language")]
	public string Language { get; set; }

	[JsonProperty(PropertyName = "TemplateId")]
	public string TemplateId { get; set; }

	[JsonProperty(PropertyName = "EmailSubject")]
	public string EmailSubject { get; set; }

	public string GetPartitionKeyValueAsProp => NotificationType.ToString();
	
	[JsonProperty(PropertyName = "_ts")]
	public long Timestamp { get; set; }

	[JsonIgnore]
	public DateTime TimestampAsDateTime => DateTimeOffset.FromUnixTimeSeconds(Timestamp).DateTime;
}
```

This will output:

```json
{
  "NotificationType": 7,
  "NotificationSubType": "some sub type",
  "Language": "en-US",
  "TemplateId": "4d5f525d-f972-42f2-9dcb-ac829abcb2c8",
  "EmailSubject": "Hello world!",
  "GetPartitionKeyValueAsProp": "7",
  "_ts": 638247631742916771
}
```

The only advice I have is to delete your existing container, and create a new one using this Library - and the new partition key type will be a `string`. You could copy over the existing email templates into this new container. I'm sorry.

**Comment by IEvangelist** [comment]
I'm going to close this as `by-design`.
