### ISSUE TITLE
IItem default implementation?

### ISSUE THREAD

**Issue by dcuccia** [IEvangelist/azure-cosmos-dotnet-repository#35]
Very cool abstraction, thank you! This is more of a "discussion," but just curious since it's so lightweight, whether you think a C# 8 "IItem" [default interface implementation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods) would suffice as a substitute for the concrete [Item](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/Item.cs) class. The use case here would be to support an existing model class hierarchy and hang these "traits" off that implementation. Id and Type currently require a backing field, which I'm not sure how to best accomplish this in that case. Just a thought! :)

**Comment by dcuccia** [comment]
Think I answered my own question at the end, there - not a full solution, as backing fields are still needed. The IItem abstraction would probably still be helpful, as it would allow other parent entity types to implement the same base item logic. Here's an example that has tests passing:

https://github.com/dcuccia/azure-cosmos-dotnet-repository

Let me know if there's an interest. Happy to clean up for a PR.

David

**Comment by IEvangelist** [comment]
Hi @dcuccia - I just now saw this, sorry for the delay. Hmmm, I see what you're saying...thanks for adding an example. I do like that, it makes sense and allows for a bit more flexibility. If you put together a PR with this, I'd consider merging it with a few minor updates. One thing I cannot do though, is move up to `netstandard2.1`.

**Comment by dcuccia** [comment]
@IEvangelist thanks for your reply! For your reference, I just the PR together for your review [here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/36), which cleaned some things up, reverted to netstandard2.0 (was just left over from playing with default interface implementation), and added a trivial usage in the tests. No pressure here - just a thought - but let me know if I can help further. :)
