### ISSUE TITLE
Provide a way to integrate with AspNetCore.Diagnostics.HealthChecks

### ISSUE THREAD

**Issue by philip-reed** [IEvangelist/azure-cosmos-dotnet-repository#366]
**Is your feature request related to a problem? Please describe.**
The latest version (7.1.0) of `AspNetCore.Diagnostics.HealthChecks` for CosmosDB requires that the CosmosClient be made available to the HealthCheck Api.

See breaking changes here.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/README.md#breaking-changes

**Describe the solution you'd like**
Consider a way to either integrate the health check package, or a way to expose the CosmosClient to allow it be passed to the HealthCheck API

**Describe alternatives you've considered**
Could maybe expose public property on `ICosmosClientProvider ` to expose the CosmosClient, and make `ICosmosClientProvider ` public?

**Comment by mumby0168** [comment]
It would be nice to create a new package in this repo that makes use of the references health checks library and can be scan either the types for there containers via the attributes and/or look at the container builder setup to automatically generate health checks for all containers used in a solution that's using the cosmos repo package.
