### ISSUE TITLE
New class Attribute to customize container for item

### ISSUE THREAD

**Issue by evenlee** [IEvangelist/azure-cosmos-dotnet-repository#39]
**Is your feature request related to a problem? Please describe.**
I want to put some items in one container, but seems current setting only allows one item one container

**Describe the solution you'd like**
An attribute like partitionkey attribute on class should be good

**Describe alternatives you've considered**
no alternative I think

**Additional context**
none

**Comment by IEvangelist** [comment]
There is an option to have a single item per container, or you can have all items share a single container. The choice is yours, but you cannot currently mix-and-match. I'm closing this for now, as I do not plan to change this now.

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/Options/RepositoryOptions.cs#L55

**Comment by evenlee** [comment]
Thanks @IEvangelist, I still think the feature will make the sdk more flexible, but i  respect your decision, i will fork you code and try to make some changes:)

**Comment by evenlee** [comment]
I want to mix the containers, like class A,B,C uses container 1, but C,D,E uses container 2, the easiest way is to add an attribute to the class like:

       [Container("Container1")]
       public class A:CosmosDbBaseItem{}

       [Container("Container1")]
       public class B:CosmosDbBaseItem{}

        Container("Container2")
        Class D{}

I've implemented it, my pleasure if you would merge it :).
a new Attribute:

                       public sealed class ContainerAttribute : Attribute
                       {
                        public string Name { get; } = "";
                
                        public ContainerAttribute(string name) =>
                            Name = name ?? throw new ArgumentNullException(nameof(name), "A name is required.");

and a new method to get the container name in DefaultCosmosContainerProvider

                 ContainerProperties containerProperties = new ContainerProperties
                    {
                        Id = _options.ContainerPerItemType ? GetContainerName() : _options.ContainerId,
                      .......

                 private string GetContainerName()
                  {
                      var itemType = typeof(TItem);
                      ContainerAttribute attribute =
                          Attribute.GetCustomAttribute(itemType, typeof(ContainerAttribute))
                          as ContainerAttribute;
          
                      return attribute?.Name ?? itemType.Name;
                  }

**Comment by IEvangelist** [comment]
Ah, ok - that makes a lot more sense now. I was a bit confused. I could probably add that.

**Comment by evenlee** [comment]
Thanks, that will be great:).

**Comment by IEvangelist** [comment]
Hey @evenlee - I've been buried lately, would you be interested in creating a PR to introduce this new feature?

**Comment by evenlee** [comment]
Thanks @IEvangelist, I tried, but seems I have not permission to push. I've uploaded the code [here](https://github.com/evenlee/azure-cosmos-dotnet-repository), please review.

**Comment by IEvangelist** [comment]
Part of v2.1.6
