### ISSUE TITLE
Access to CosmosClient creation

### ISSUE THREAD

**Issue by joelsteventurner** [IEvangelist/azure-cosmos-dotnet-repository#398]
I've been using this framework and am generally very happy with it, but I have run into a couple scenarios where the framework makes it difficult to do certain things. These issues all seem to stem from the fact that the CosmosClient instantiation is inaccessible.

The 2 scenarios that are proving problematic to me are as follows:
1) Multi-tenancy, where I have a single application and each tenant has their own Cosmos instance

In this scenario I'd ideally want a cached `CosmosClient` per tenant, but the framework has a singleton `CosmosClient` and the factory interface for this `ICosmosClientProvider` is internal so I see no way to easily extend this.

2) Automated Integration testing against a dockerized cosmos emulator

Here I am using `Microsoft.AspNetCore.Mvc.Testing` along with `Testcontainers.CosmosDb` to write automated integration tests.  In this scenario I need to as part of the tests reconfigure my application, see example below. Here you can see the need for `CosmosClient` re-configuration / customization.

![image](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/assets/11704606/35086e88-8fe0-48d9-94fe-d264bd2918d0)

The feature I'd like to simply making the `ICosmosClientProvider` interface public so that custom implementations can be supplied.
Or more generally make it such that there is a factory which creates the `CosmosClient`, which can have its implementation swapped out.

This would allow me to create a `MultiTenantCosmosClientProvider` and an `IntegrationCosmosClientProvider` which I beleive would solve these issues.

**Comment by IEvangelist** [comment]
Hi @joelsteventurner - thank you for your kind words, and ideas here. I know that others have specifically asked for multitenancy support, that would be awesome to add! As for the idea around exposing the `ICosmosClientProvider`, I'm not opposed to that idea either. I recently helped with an addition to .NET Aspire to add emulator support, and I believe we should absolutely add that here too!

I love contributions, and I'm happy to work with you on making those a reality. What do you think?

**Comment by joelsteventurner** [comment]
Hi @IEvangelist , that sounds great.

I'll submit a pull request for changing the interface accessibility from internal to public.

**Comment by joelsteventurner** [comment]
@IEvangelist  submitted the pull request.

**Comment by IEvangelist** [comment]
Closing this as #403 fixed it
