### ISSUE TITLE
Refactor areas of the code that have high cyclomatic complexity

### ISSUE THREAD

**Issue by IEvangelist** [IEvangelist/azure-cosmos-dotnet-repository#41]
Evaluate the _[CODE_METRICS.md](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/CODE_METRICS.md)_ file and determine which areas could use improvement, based on the highest levels of cyclomatic complexity. Refactor into smaller, more manageable / testable bits.

**Comment by mumby0168** [comment]
Going to close this issue as the latest set of PR's have reduced all of these down from the warning level from the code metrics pipeline see below:

![image](https://user-images.githubusercontent.com/23740684/132243386-4f0bb086-4b29-4839-b8d7-f7eeb78229d6.png)
