### ISSUE TITLE
Minimum Autoscale Throughput should be as low as 1000 RU/s

### ISSUE THREAD

**Issue by bogdan-rusu-arnia** [IEvangelist/azure-cosmos-dotnet-repository#425]
**Describe the bug**
As specified in the  [documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/autoscale-faq#what-s-the-entry-point-ru-s-for-autoscale-) the minimum autoscale throughput can be as low as 1000 RU/s from April 2022. The current implementation is using the old minimum value 4000 RU/s.

**To Reproduce**
Try to create a new container using `containerOptionsBuilder.WithAutoscaleThroughput()` using a value `1000 < maxAutoScaleThroughput < 4000 `

**Expected behavior**
The container should be created successfully without any error being thrown.

**Actual behavior**
The following error is thrown `Autoscale throughput must be between 4,000 and 1,000,000 RUs.`

**Comment by IEvangelist** [comment]
Thank you for posting this issue, would you be interested in helping contribute to this project - a fix in the form of a PR? I'd be more than happy to review it, looks like you'd want to start here:

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/src/Microsoft.Azure.CosmosRepository/Builders/ContainerOptionsBuilder.cs#L121
