### ISSUE TITLE
Explore source generators as an alternative to reflection-based attribute usage

### ISSUE THREAD

**Issue by IEvangelist** [IEvangelist/azure-cosmos-dotnet-repository#43]
Currently there are several attributes that are exposed to consumers:

- `PartitionKeyPath`
- `Container`

These attributes are used to declaratively serve as a means for specifying the partition key path of an item or the container an item should belong to respectively. It would be nice to avoid reflection-based attribute usage, and instead source generate the implementation details - but that might be a breaking change, as `partial` item classes might be required... nonetheless, explore it.

**Comment by mumby0168** [comment]
In order to avoid attribute usage could the `Item` classes define these as  readonly properties that are forced to be implemented or could this be driven by some more `ServiceCollectionExtensions` something like this maybe

```csharp

services.AddRepository(options => 
{
    options.ContainerName = "foo";
    options.PartitionKey = "/bar";
});

```

Only ideas but it would remove the need for reflection.

**Comment by IEvangelist** [comment]
Yeah, this is probably not worth the effort and would be a breaking change.
