### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by mustafarabie** [IEvangelist/azure-cosmos-dotnet-repository#439]
### Discussed in https://github.com/IEvangelist/azure-cosmos-dotnet-repository/discussions/438

<div type='discussions-op-text'>

<sup>Originally posted by **mustafarabie** May 12, 2024</sup>
After adding the latest version of the Repository nuget, the Startup.cs give the following error:
Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Has anyone run into this before?

Referenced Packages in my project
"Microsoft.NET.Sdk.Functions" Version="4.4.0"
"Microsoft.Extensions.DependencyInjection" Version="8.0.0" 
"FirebaseAdmin" Version="3.0.0" 
"FirebaseAdminAuthentication.DependencyInjection" Version="1.1.0"
"Microsoft.Azure.Functions.Extensions" Version="1.1.0"
"Newtonsoft.Json" Version="13.0.3"
"HtmlAgilityPack" Version="1.11.61"

Thanks</div>

**Comment by IEvangelist** [comment]
Hi @mustafarabie - so you're using the latest version `8.1.5`? What TFM is your consuming project targeting? In accordance with the dependencies for the package, this is the same as it was in previous versions: https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository#dependencies-body-tab. I'm going to need more detail, but I'd recommend cleaning the solution:

```
dotnet clean
```

**Comment by mustafarabie** [comment]
Hi @IEvangelist I am using the latest version 8.1.5.
TargetFramework: net6.0
AzureFunctionsVersion: v4

I did clean and tried out with a completely new test Azure Function.

I noticed that from 7.0.0->8.1.15 targets .Net 7/8. This might be the issue.
I believe that this is the issue. I installed version 3.7.0 and I am not getting the error anymore.

Thank you

**Comment by IEvangelist** [comment]
Trying targeting v7 for your function

**Comment by IEvangelist** [comment]
I'm going to close this as I'm not seeing a reply, and I think the issue was resolved. Happy to reopen this if need be.
