### ISSUE TITLE
You're required to use version 2.14 for Azure Functions

### ISSUE THREAD

**Issue by andrewalderson** [IEvangelist/azure-cosmos-dotnet-repository#45]
*Original title: Upgrade to C# 9.0 breaks azure functions*

I am not sure if you are aware of this, and I don't consider it a bug but maybe it will save some other people some time. Versions of this library that target C# 9 (after 2.14) break azure functions with aspnetcore 3.1. The Azure Functions sample in this repository doesn't work anymore.

I won't be upgrading my function apps until .NET 6 is released so for now I will stick with 2.14.

**Comment by IEvangelist** [comment]
Thank you for this callout, I'm going to pin this issue for others - to make it more visible.

# TL;DR;

**Use version 2.14 for Azure Functions.**

**Comment by IEvangelist** [comment]
[Fixed with v2.2.0](https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository/2.2.0)
