### ISSUE TITLE
Unique-Key constraint configurable

### ISSUE THREAD

**Issue by VeryCautious** [IEvangelist/azure-cosmos-dotnet-repository#46]
There is not jet a possibility to create containers with a unique-key-constraint.

Because of that it would be great if one could specify those. Maybe one could add an attribute to the Property that should be unique, int the Item that implaments the IItem interface.

Then when a container is created, the type it is created for is checked for this attribute.

**Comment by IEvangelist** [comment]
@VeryCautious  I was just publishing version 2.1.7 when I realized that the `UniqueKeyAttribute` was private. It wouldn't have been exposed to any consumers, not sure how I missed that in the code review - but I need to fix that first. LOL

**Comment by IEvangelist** [comment]
This is in version 2.1.8:
https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository/2.1.8

Should be live soon! Thanks again
