### ISSUE TITLE
When to use Cosmos IRepository vs. EF Core DB Provider for Cosmos

### ISSUE THREAD

**Issue by tafs7** [IEvangelist/azure-cosmos-dotnet-repository#5]
Would love to understand reasons why/when one choose this `IRepository` API for Cosmos over the EF Core DB provider for Cosmos.

There's some overlap in functionality since EF Core's `DbSet<T>` is essentially like an `IRepository<T>`, right? Perhaps this answer might be worth adding to the readme or wiki, so it's not buried is this GH issue.

**Comment by IEvangelist** [comment]
Hi @tafs7 - I hope all is well. Thank you for posting this issue, and asking this question. I saw your ask earlier on the CosmosDB blog and responded there, before seeing this. My answer is the same, this is just another tool - I'm not too familiar with the official EF Core DB provider - but I can tell you what someone has said who has used both:

> It’s smaller, faster, and simpler than the EF provider by a wide margin

This is their opinion. In looking at the API of the EF provider, it does look a lot more complex - but I'm a bit biased. This is an unofficial .NET SDK. So, there are going to be pros and cons. I'll leave it up to you to decide which you'd prefer. Does that make sense? Do you have any specific questions as it relates to comparing them?

**Comment by IEvangelist** [comment]
I'm going to close this for now, but if you feel as though I haven't answered the question or if you want to continue to discuss it - we can reopen it. Thanks again.
