### ISSUE TITLE
Need feature to disable or override "type" property with other name

### ISSUE THREAD

**Issue by anujrhicstech** [IEvangelist/azure-cosmos-dotnet-repository#50]
I already have a property in my class and cosmos Db named "type",
which causes the issue when retrieving an item as the type field is in CosmosDb and Repository Item so we have a conflict.

Could you please add a feature so we can disable the Item class's "type" property if not required? OR
If we can override/rename it with some other property name.

Also, can we use UnitOfWork with your current repository?

**Comment by IEvangelist** [comment]
I am sorry for the concern here, by "type" is a reserved property name of this package. I'd be open to reviewing a PR to adjust or extend this functionality as you've suggested - but I'd be hesitant to do so.

You are free to just a `JsonPropertyName` value to change your `Type` property to something else. Would that work?

**Comment by mumby0168** [comment]
@anujrhicstech Hi, was there anything else to add on this? I think I agree with @IEvangelist this unfortunately would be a reserved property for this package. If there is nothing more on this would you be okay if was to close the issue?

**Comment by mumby0168** [comment]
I am going to close this issue now I think we have provided a suitable workaround for this.
