### ISSUE TITLE
Feature request: pagination support

### ISSUE THREAD

**Issue by evenlee** [IEvangelist/azure-cosmos-dotnet-repository#53]
When we get items from repo, if the count of items is more than several thousands, a better way is to get data by page, can we support it?

**Comment by IEvangelist** [comment]
Hi @evenlee - that is a great idea, I'd love to review a PR for this addition. Would you be willing to create a pull request to add this functionality?

**Comment by anujrhicstech** [comment]
Hi IEvanelist,

I was trying to create a custom pagination functionality but facing following issue, could you please help me with that
"DocType" is my partition key field

1) for PaginationDto, First I am trying to get total count of records

if (Paginate.TotalCount == 0)
            {
                QueryDefinition queryCount = new QueryDefinition("SELECT count(c.DocType ) FROM c WHERE c.DocType ='" + _partitionKey + "' and c.active=true");
                var count = (await _repository.GetByQueryAsync(queryCount)).Single();
                result.TotalCount = count;
            }
     But here as the repository of account class it returns IEnumerable<Accounts> but according to query it should return on single integer, 
     How can i get only the interger (how to fetch the single value) 
---------------------------------------------------------------------------------------------------------------------------
2) IMPORTANT - How can i fetch/Retrive the "Continuation token" and use in the following query

            QueryDefinition queryDefinition =
                new QueryDefinition("SELECT * FROM c WHERE c.DocType ='" + _partitionKey + "' ORDER BY c.createdOn DESC OFFSET " + ((result.CurrentPage*result.PageSize)-result.PageSize) + " LIMIT " + paginate.PageSize + "");

            var temp = await _repository.GetByQueryAsync(queryDefinition);
            result.Items = temp;
            return result;
--------------------------------------------------------------------------------------------------------------------------------
Reference :- https://medium.com/swlh/pagination-and-searching-in-asp-net-core-api-using-cosmos-db-869384a59f5
Reference 2 :https://medium.com/@gary.strange/understanding-cosmosdb-continuation-tokens-hasmoreresults-and-connectionpolicy-requesttimeouts-3ed1fadfa81d

**Comment by evenlee** [comment]
Thanks @anujrhicstech for the starting. @IEvangelist I have not got time to investigate yet, will start it soon.

**Comment by deepbass** [comment]
second this, love this library and would love this feature. I'll try and carve out some time to help as it has the up for grabs tag - is there a contributor guide or something?

**Comment by IEvangelist** [comment]
I @deepbass - I haven't put together a contributor guide yet. But contributions are most successful when starting as an issue, formalizing a plan through discussion and then creating a pull request. The pull request should include unit tests, and follow all of the existing naming conventions and styling. The pull request shouldn't include changes to existing infrastructure unless explicitly stated. It sounds like this is to add a new API - wherever pagination is possible we'd add the supporting APIs.

See: https://docs.microsoft.com/azure/cosmos-db/sql-query-pagination

**Comment by emrekara37** [comment]
> Thanks @anujrhicstech for the starting. @IEvangelist I have not got time to investigate yet, will start it soon.

Hi @evenlee ,

i want to implement this feature too , if you didn't start we can start together or i can support to you

**Comment by zhangzunke** [comment]
Hi @emrekara37  and @evenlee,
I am working on this feature, the PR has been created, and ready for approval.

**Comment by anujrhicstech** [comment]
@IEvangelist , its seems @zhangzunke addressed the requested changes, are there anymore changes required ? or can you please review, merge and release it

**Comment by IEvangelist** [comment]
> @IEvangelist , its seems @zhangzunke addressed the requested changes, are there anymore changes required ? or can you please review, merge and release it

Hi @anujrhicstech - I'm still reviewing it, there are a few conceptual / design decisions that I'm thinking about. But it is much closer! Stay tuned...

**Comment by anujrhicstech** [comment]
Hi @IEvangelist ,
Have you completed the review of this pull request, are any changes required. 
Just awaiting get this update into my test project. Any idea when this pull request might be processed.

Thanks

> > @IEvangelist , its seems @zhangzunke addressed the requested changes, are there anymore changes required ? or can you please review, merge and release it
> 
> Hi @anujrhicstech - I'm still reviewing it, there are a few conceptual / design decisions that I'm thinking about. But it is much closer! Stay tuned...

Hi @IEvangelist ,
Have you completed the review of this pull request, are any changes required. 
Just awaiting get this update into my test project. Any idea when this pull request might be processed.

Thanks

**Comment by IEvangelist** [comment]
Hi @anujrhicstech - we've been waffling over this for a while now and decided that the proposed PR wasn't the correct implementation. We all agree that the feature should exist, but we just need to implement it correctly. See some of the comments in the PR, and this in particular : https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/57#issuecomment-878343483

**Comment by mumby0168** [comment]
Also may be good to refer to based on https://github.com/IEvangelist/azure-cosmos-dotnet-repository/pull/57#issuecomment-878343483 a jump straight to the issue in the ef-core implementation for cosmos https://github.com/dotnet/efcore/issues/24513

**Comment by mumby0168** [comment]
Some more information on continuation tokens https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-pagination#continuation-tokens

**Comment by Rabosa616** [comment]
I´ve modified localy your code on the pagination branch to use skip and take
I´ve removed  the continuationToken and rename the lastPage by pageNumber.
Then add on the DefaultRepository.cs at line 300 this:

``
 query = query.Skip(pageSize * (pageNumber - 1)).Take(pageSize);
``

I´ve did several tests and works as expected.

**Comment by mumby0168** [comment]
Hey, @Rabosa616 @evenlee @anujrhicstech @zhangzunke @deepbass we have just merged and released our first take on paging make use of continuation tokens see PR #142 this includes an example and works for a load more paging scenario.
