### ISSUE TITLE
Selecting a partition key in an item class

### ISSUE THREAD

**Issue by jeminpro** [IEvangelist/azure-cosmos-dotnet-repository#55]
This is an excellent package that makes it working with Cosmos DB a breeze. However, as there is a limit of 20GB per partition key and currently partitions defaulted per type, we cannot use this library on enterprise projects where data could be a lot bigger per partition. 

Is it possible to select a partition key via JsonProperty so that the partition key can be specified within a repository item so that when ContainerPerItemType is set to true it can be used for larger data?

I am not sure if this is already implemented as it is not documented in the repository or blog post.

**Comment by IEvangelist** [comment]
Hi @jeminpro - thank you for your kind words. Yes, I believe that there is an existing solution -- does this address your concerns, see: https://github.com/IEvangelist/azure-cosmos-dotnet-repository#advanced-partitioning-strategy
