### ISSUE TITLE
Multiple containers support

### ISSUE THREAD

**Issue by farcasclaudiu** [IEvangelist/azure-cosmos-dotnet-repository#58]
Just a question:
Is it possible to support multiple containers (eg: one container for data, another container for audit) ?

**Comment by IEvangelist** [comment]
Hi @farcasclaudiu - as of right now, the answer is "no". But this is something that I've been thinking would be nice to have. It would require changing a lot of infrastructure, and might even be a breaking change if not done correctly. There would need to be a lot of design discussion around this as there are many ways it could be configured, for example:

- How should we indicate which Item belongs to which container?
  - If we decide to implement this with attributes, how would we avoid impacting existing usage and what are reasonable defaults?
- If this is done from a configuration stand-point, should the config define the item types that it would contain?

**Comment by farcasclaudiu** [comment]
I will be tempted to say "neither".
My idea will be to have the cosmosdb factory resolving each specific IRepository based on a specified name (string key).
Then it should be up to the developer what entities/types he will be using with each and every IRepository.

Ex:
_personRepository = repositoryFactory.GetFactory<Person>("data");
_repositoryAudit = repositoryFactory.GetFactory<AuditInfo>("audit");

But indeed, it might not be that simple.

**Comment by IEvangelist** [comment]
This was addressed as part of #77 - do you think we might be able to close this one @farcasclaudiu?

**Comment by farcasclaudiu** [comment]
> This was addressed as part of #77 - do you think we might be able to close this one @farcasclaudiu?

Ok, let's close it.

**Comment by farcasclaudiu** [comment]
closed as resolved.

**Comment by sven5** [comment]
@IEvangelist  How to configure this? I couldn't find any information.  Please share an example when using two containers.
Thanks

**Comment by IEvangelist** [comment]
> @IEvangelist How to configure this? I couldn't find any information. Please share an example when using two containers. Thanks

Hi @sven5 - you can configure `ContainerPerItemType` to `true`, and you'll end up with a container per item type. See https://ievangelist.github.io/azure-cosmos-dotnet-repository/#advanced-partitioning-strategy, does that help?

**Comment by sven5** [comment]
@IEvangelist  Yep, I was missing the `ContainerPerItemType` setting.
