### ISSUE TITLE
Transforming the model in a GET response

### ISSUE THREAD

**Issue by CarloGarcia** [IEvangelist/azure-cosmos-dotnet-repository#59]
I would like to return a different model (POCO class that derives from Item) on some GET responses/read operations for a given repository.

This model would be a cut down version of the "main" model and only return the fields specified in the query that is sent to CosmosDb.

Let's say we have a "Person" entity and, instead of returning the full JSON payload for an entire person, the SQL query provided to CosmosDb would contain a subset of the fields. For example: "```SELECT c.firstName, c.lastName, c.dob, c.status FROM c WHERE c....```". (so here we are only returning 4 fields).

Unless I am missing something, it seems that, at the moment, because the repositories are typed to a single model, one can only retrieve that one full entity and can't get CosmosDb onto retrieve a subset if the fields for the entity. 

For large documents this could be an issue brining all the data for an entity across the wire to the calling Web API needlessly only to be discarded by the API before sending to the client (API consumer). It could also be an issue for sensitive data.

Is the only way to get around this for now to create multiple [additional] repositories (one for each subset of response fields) for the same container/entity in Cosmos Db?

**Comment by mumby0168** [comment]
Hi think I ran into a very similar problem as this we wanted a more condensed version of a type, the way we did this was to create another type with less properties, and set the container name and partition key attributes to be the same as the original type, the trick is to set the Type field on the smaller object to be an empty string then when reading back it passes this check below:

```csharp
return item is { Type: { Length: 0 } } || item.Type == typeof(TItem).Name ? item : default;
```

Source code is [here](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/DefaultRepository.cs) line 69.

**Comment by CarloGarcia** [comment]
That did the trick for me, thanks!
