### ISSUE TITLE
In memory running option

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#60]
**Is your feature request related to a problem? Please describe.**
`n/a`

**Describe the solution you'd like**
It would be useful to have a implementation of the `IRepository<T>` which would run an in memory store much like what EF core provides. Matching the cosmos API wherever possible for use alongside the `Microsoft.AspNetCore.Mvc.Testing` nuget package. This would be great for running integration tests in pipelines.

**Describe alternatives you've considered**
Running test's against a real version of cosmos locally or in Azure.

**Additional context**
`n/a`

**Comment by IEvangelist** [comment]
I love this idea, @mumby0168 - I could easily imagine a companion repository and NuGet package that provides this testing capabilities. Would you expect it to be within this package - perhaps something like this?

```csharp
services.AddInMemoryCosmosRepository(...)
```

**Comment by mumby0168** [comment]
Yeah that would be the plan just a different implementation of `DefaultRepository<T>` was my idea half started this idea in a project I am working on at the moment but having it as part of the package would be great.

Only slight issue I maybe see is mapping the SQL overloads for GetAsync to an internal list sure it is something that can be worked out however.

**Comment by mumby0168** [comment]
Hi @IEvangelist I am currently working on this first commit is here all be it very basic, wanted to get your feedback as I work through it, would it be best to keep a PR as a draft into this repository from my fork or just wait until I am ready?

https://github.com/mumby0168/azure-cosmos-dotnet-repository/commit/44f3c41993a2de419901b77d24f84f81d650d070

Thanks,
Billy

**Comment by IEvangelist** [comment]
Hi Billy, that is a great start - added a few comments.

**Comment by mumby0168** [comment]
Thank you, will work through this over the next few weeks, on holiday next week so might be a slow start haha. Thanks for your time 👍

**Comment by dcuccia** [comment]
This would be great. I've been working against the Linux Docker Cosmos DB emulator, but it's a bit heavy and SSL gets in the way.

**Comment by mumby0168** [comment]
Hello again @IEvangelist I have pretty much finished the basics of the implementation.

I have added a small section to the docs.

I was wondering is it worth adding a sample using `Microsoft.AspNetCore.Mvc.Testing` against the web tier project?

Also having thinking that supporting the following methods:

```csharp
/// <inheritdoc/>
        public ValueTask<IEnumerable<TItem>> GetByQueryAsync(string query, CancellationToken cancellationToken = default)
        {
            throw new NotImplementedException();
        }

        /// <inheritdoc/>
        public ValueTask<IEnumerable<TItem>> GetByQueryAsync(QueryDefinition queryDefinition, CancellationToken cancellationToken = default)
        {
            throw new NotImplementedException();
        }
```

Any tips or plan of attack would be appreciated.

**Comment by pingdong** [comment]
Hi, mumby0168. I didn't make last Saturday meeting. 

For temporary solution, that way I'm using

For integration testing, testing against the real cosmos db is prefer. I had a discussion with our MS consultant about it.

Secondary, for local unit testing, you could use local cosmos emulator. If you want to run those unit tests in pipeline. You could use windows image. It has cosmos emulator built-in, but you need spin the emulator up by two lines of PowerShell script.

Import-Module "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator"
Start-CosmosDbEmulator

**Comment by mumby0168** [comment]
> Hi, mumby0168. I didn't make last Saturday meeting.
> 
> For temporary solution, that way I'm using
> 
> For integration testing, testing against the real cosmos db is prefer. I had a discussion with our MS consultant about it.
> 
> Secondary, for local unit testing, you could use local cosmos emulator. If you want to run those unit tests in pipeline. You could use windows image. It has cosmos emulator built-in, but you need spin the emulator up by two lines of PowerShell script.
> 
> Import-Module "C:/Program Files/Azure Cosmos DB Emulator/PSModules/Microsoft.Azure.CosmosDB.Emulator"
> Start-CosmosDbEmulator

Hi, yes we have an option to this in our integration tests currently we can either run in memory mode or against the real services in the way you have described. 

We have seen benefit in terms of speed of running tests in this way using an in memory model, but do hope to run tests on a nightly against a real Cosmos DB service.

**Comment by pingdong** [comment]
I guess you don't want tests pollute each other. We have a similar issue before, now we run them is parallel by isolating each test.
