### ISSUE TITLE
Community chatroom

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#67]
**Is your feature request related to a problem? Please describe.**
`n/a`

**Describe the solution you'd like**
A chatroom for the community, `Discord` would be my suggestion, no reason we can't have more than one?

**Describe alternatives you've considered**
`n/a`

**Additional context**
`n/a`

**Comment by dcuccia** [comment]
Discord sounds great to me, @mumby0168

**Comment by mumby0168** [comment]
I'll hang on for anymore opinions then if not I can create the channel and i'll update the docs to include a link 👍

**Comment by z3le** [comment]
+1 for discord

**Comment by jvilomar** [comment]
I will be ok with whatever you decide guys.

**Comment by mumby0168** [comment]
Hi all discord link is here: https://discord.gg/pRsUTJM9

**Comment by mumby0168** [comment]
Link that will not expire: https://discord.gg/qMXrX4shAv
