### ISSUE TITLE
Async methods CancellationToken

### ISSUE THREAD

**Issue by 3GDXC** [IEvangelist/azure-cosmos-dotnet-repository#7]
Please allow the developer can pass a CancellationToken to the Async methods; thus allowing timeout cancellations etc. for long running tasks

**Comment by IEvangelist** [comment]
Hi @3GDXC - I labeled this as up for grabs. Feel free to send a pull request my way.

**Comment by IEvangelist** [comment]
Hi again, @3GDXC - I started working on this. I'll include optional parameters for the `CancellationToken`. Look for that in the next patch version, since they'll be optional they are technically opt-in and non-API breaking.

**Comment by wforney** [comment]
I did this on the enumerable methods in that last PR. I'll include this in my next one.

**Comment by wforney** [comment]
I don't mind deferring until @3GDXC does this part...

**Comment by wforney** [comment]
I went ahead and did this in the repository in my last PR.

**Comment by IEvangelist** [comment]
Added here https://github.com/IEvangelist/azure-cosmos-dotnet-repository/commit/227c05d00fa7a7e03487e05417c70a8104a8f133

**Comment by 3GDXC** [comment]
great work, and thanks, looking at using this in a new development of a eCommerce application

**Comment by IEvangelist** [comment]
Live in [version 2.0.3](https://www.nuget.org/packages/IEvangelist.Azure.CosmosRepository/2.0.3)
