### ISSUE TITLE
Set TTL (Time to live) at Item Level

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#79]
**Is your feature request related to a problem? Please describe.**
`n/a`

**Describe the solution you'd like**
A way to configure a `TimeSpan` or seconds for an item to live for after it has been created.

**Describe alternatives you've considered**
Manually setting this as a the `ttl` property on a class that already implements `Item` or `IItem`

**Additional context**
`n/a`

**Comment by IEvangelist** [comment]
Closed as implemented in #150
