### ISSUE TITLE
Transactions and optimistic concurrency control

### ISSUE THREAD

**Issue by andrcami** [IEvangelist/azure-cosmos-dotnet-repository#83]
Hi I am working on a project that is using your library, the project requires that we handle some form of Transactions or optimistic concurrency control on the data. Essentially I need to read the data and change contents within the document and write it back.

What I want to avoid is when writing back to have a newer version in the database and my data ends up overwriting the current document. 

Microsoft has already something that handles such situations (https://docs.microsoft.com/en-us/azure/cosmos-db/database-transactions-optimistic-concurrency#optimistic-concurrency-control) is this implemented within your library?

**Comment by mumby0168** [comment]
I have seen this demo https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L676-L772 linked at the bottom of that document, it certainly sounds like something we should be looking into. It would be interesting to better understand how the native client supports this and what our API should look like to neatly wrap up this feature.

**Comment by mumby0168** [comment]
@andrcami going to look at implementing this would you expect to see if just for upserts?

**Comment by lappy4711** [comment]
I concur with andrcami, it is a much needed feature....I am currently stuck in my project due to overwrite issues.

**Comment by IEvangelist** [comment]
> I concur with andrcami, it is a much needed feature....I am currently stuck in my project due to overwrite issues.

Hi @lappy4711 - to be clear, I want to make sure that you're using this SDK - is that correct? Or are you using the official Cosmos DB SDK?

**Comment by lappy4711** [comment]
> > I concur with andrcami, it is a much needed feature....I am currently stuck in my project due to overwrite issues.
> 
> Hi @lappy4711 - to be clear, I want to make sure that you're using this SDK - is that correct? Or are you using the official Cosmos DB SDK?

Yes, I am using the SDK....really like the simplicity.

**Comment by mumby0168** [comment]
I am going to look at it next week currently away 🇵🇹. My only concern is having to store the 'etag' on the 'Item' may result in a breaking change 🤔

**Comment by lappy4711** [comment]
> I am going to look at it next week currently away 🇵🇹. My only concern is having to store the 'etag' on the 'Item' may result in a breaking change 🤔

Why would you have to to that? You already have the _etag.

**Comment by mumby0168** [comment]
> > I am going to look at it next week currently away 🇵🇹. My only concern is having to store the 'etag' on the 'Item' may result in a breaking change 🤔
> 
> 
> 
> Why would you have to do that? You already have the _etag. Can't you just use that for whatever cool strategy you come up with? Personally, I would just need an exception that indicates that I'm attempting to overwrite data that is newer than the one I currently have. I could then fetch the data and try again. Or similar. 

Yes we would probably keep with the same exception that the SDK that cosmos throws can't remember the status code off the top of my head.

What I meant by the etag was we would need a field on our base class 'Item' and also on our interface 'IItem' which could result in a breaking change. We would need this as we would have to use the etag when we are upsetting a document.

**Comment by mumby0168** [comment]
Hi @andrcami we are on with this, see #147 😄

**Comment by mumby0168** [comment]
Hi @andrcami @lappy4711 closing this issue now, the PR has been merged and we are waiting on #79 & #92 before we cut a release @robertbennett1998 is working on this and should be done soon 😃
