### ISSUE TITLE
Implement CountAsync<TItem>

### ISSUE THREAD

**Issue by CarloGarcia** [IEvangelist/azure-cosmos-dotnet-repository#84]
I would like to request a count of records for a given filter criteria/query. For example:
`SELECT VALUE COUNT(1) FROM c WHERE c....`

When querying CosmosDb directly, this returns a response as follows:
```
[
    27
]
``` 
(In the example above, there are 27 records)

Using the repository, this doesn't seem possible. Is there a way to use the existing repository to get the above result back, or would a new method be required?

Since all POCOs must derive from IItem, I have tried to create a POCO for the anonymous array response type above but have faced some challenges (with deserialization, etc). I don't this its possible (but could be wrong, only spent a few minutes experimenting).

**Comment by IEvangelist** [comment]
@dcuccia @mumby0168 we should consider adding this to the repos API. Perhaps a `ValueTask<int> CountAsync` for a given `IRepository<TItem>`, should be easy.

**Comment by mumby0168** [comment]
Yeah certainly can be done, I have been thinking about an 'ExistsAsync' also.

**Comment by IEvangelist** [comment]
> Yeah certainly can be done, I have been thinking about an `ExistsAsync` also.

Yes, let's track these new APIs separately. But I think they're great and easy additions.

**Comment by mumby0168** [comment]
Hi @CarloGarcia would you fancy having ago at implementing this? Feel free to open a draft PR with your idea if you want some feedback 👍

**Comment by kevin-benton** [comment]
Is this still open for someone to take on? I have a basic implementation and tests working that I can PR and take feedback on. Currently looking into the examples to find some good places for addition.

**Comment by mumby0168** [comment]
Hi @kevin-benton we did have a PR in for this #86 but it went a little stale, be more than happy to review your PR 😃
