### ISSUE TITLE
Linq Queryable Decorator 

### ISSUE THREAD

**Issue by mumby0168** [IEvangelist/azure-cosmos-dotnet-repository#88]
Someone may know the answer to this but as we do not expose the `LinqQueryable` how would a consumer chain extra linq methods other than just a `.Where(x => ...)` clause, would we need to add some sort of extra API for this?

**Comment by IEvangelist** [comment]
That's a fair question. Instead of exposing the raw `LinqQueryable` we could expose a custom type that scopes the operators that we know are actually supported. See: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql#SupportedLinqOperators. This would prevent consumers from trying to use something that isn't supported, and we could just use like the decorator pattern or something to easily delegate out to the actual underlying operators. Does that make sense?

**Comment by mumby0168** [comment]
> @mumby0168
> 
> That's a fair question. Instead of exposing the raw `LinqQueryable` we could expose a custom type that scopes the operators that we know are actually supported. See: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql#SupportedLinqOperators. This would prevent consumers from trying to use something that isn't supported, and we could just use like the decorator pattern or something to easily delegate out to the actual underlying operators. Does that make sense?

Yes that makes sense rather than providing direct access, how would the decorator work would this replace the Expression<T> method signatures we have on the methods currently or would this be something we return to a client?

**Comment by mumby0168** [comment]
@IEvangelist I think I am following just maybe a sketch of the interface signature would clarify it for me struggling to wrap my head around what it would like 🤔

**Comment by IEvangelist** [comment]
Actually, the more I think about this - the more exposing an ordering operator doesn't really make sense. If we're returning an `IEnumerable<TItem>`, they can order that once it is materialized client-side. What's the benefit of having the server do it?

**Comment by mumby0168** [comment]
> Actually, the more I think about this - the more exposing an ordering operator doesn't really make sense. If we're returning an `IEnumerable<TItem>`, they can order that once it is materialized client-side. What's the benefit of having the server do it?

This was mainly thinking of the paging, unlikely you would want to make an unordered query and then cycle through the pages. For example most recent time stamps and look back in time as you cycle the pages?

If not I am not sure what default order it would take or if it would be repeatable if that makes sense.

**Comment by mumby0168** [comment]
> @mumby0168
> 
> That's a fair question. Instead of exposing the raw `LinqQueryable` we could expose a custom type that scopes the operators that we know are actually supported. See: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql#SupportedLinqOperators. This would prevent consumers from trying to use something that isn't supported, and we could just use like the decorator pattern or something to easily delegate out to the actual underlying operators. Does that make sense?

Assuming in terms of a decorator it would look something like this?

```csharp
await Page<Person>(decorator => decorator.Where(p => p.Age > 3).OrderBy(p => p.Age));


async Task Page<T>(Action<QueryableDecorator<T>> query)
{
    
    var client = new CosmosClient(Environment.GetEnvironmentVariable("CosmosConnectionString"));
    var database = client.GetDatabase("bm-cosmos-db");
    var container = database.GetContainer("people");



    var queryable = container.GetItemLinqQueryable<T>();
    var decorator = new QueryableDecorator<T>(queryable);
    query(decorator);

    decorator.Queryable.ToFeedIterator();
    
    //DO WORK.
}


public class QueryableDecorator<T>
{
    private IQueryable<T> _queryable;

    internal QueryableDecorator(IOrderedQueryable<T> queryable)
    {
        _queryable = queryable;
    }

    public QueryableDecorator<T> Where(Expression<Func<T, bool>> expression)
    {
        _queryable = _queryable.Where(expression);
        return this;
    }

    public QueryableDecorator<T> OrderBy<TValue>(Expression<Func<T, TValue>> expression)
    {
        _queryable = _queryable.OrderBy(expression);
        return this;
    }

    internal IQueryable<T> Queryable => _queryable;

}
```

**Comment by mumby0168** [comment]
What are your thoughts on this @bradwestness @IEvangelist @dcuccia ?

**Comment by mumby0168** [comment]
@IEvangelist what were your thoughts on this?

**Comment by mumby0168** [comment]
> > @IEvangelist what were your thoughts on this?
> 
> So this would scope the consumers to the [Supported LINQ Operators](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql#SupportedLinqOperators), if so I like it.

Yes, that would be the plan using a wrapper similar to what I put above. I was thinking just to start with the basic ones to begin with such as `OrderBy`

**Comment by IEvangelist** [comment]
> > > @IEvangelist what were your thoughts on this?
> > 
> > 
> > So this would scope the consumers to the [Supported LINQ Operators](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-linq-to-sql#SupportedLinqOperators), if so I like it.
> 
> Yes, that would be the plan using a wrapper similar to what I put above. I was thinking just to start with the basic ones to begin with such as `OrderBy`

Another quick thought, will this impact any of the new APIs, such as `CountAsync` -- since they already have support for these operators?

**Comment by mumby0168** [comment]
Yes maybe if we do this then, we won't need to expose it although it would not hurt to have two options?

**Comment by mumby0168** [comment]
@IEvangelist what are your thoughts on this API?

```csharp
        /// <summary>
        /// Get's an <see cref="IEnumerable{TItem}"/> collection of <see cref="IItem"/>
        /// </summary>
        /// <param name="queryBuilder"></param>
        /// <returns>A collection of item instances returned by the given LINQ <paramref name="queryBuilder"/> Cosmos SQL query.</returns>
        ValueTask<IEnumerable<TItem>> GetByQueryAsync(Action<CosmosQueryableDecorator<TItem>> queryBuilder);
```

This work's nicely for the LINQ operators that result in an `IQueryable<TItem>` but not so much for using operators such as `.Select(item => item.Id)` I did kind of go down the root of the this API but then this kind of break's the pattern of the whole Repository by now not returning a `TItem` this was it what do you think?

```csharp
ValueTask<TReturn> QueryAsync<TReturn>(Func<CosmosQueryableDecorator<TItem>, TReturn> queryBuilder);
```

The API above does add a lot of complications internally to the library.

**Comment by IEvangelist** [comment]
I guess my initial thoughts are that we already expose two overloads of the `GetByQueryAsync` APIs:

```csharp
ValueTask<IEnumerable<TItem>> GetByQueryAsync(
    string query,
    CancellationToken cancellationToken = default);

ValueTask<IEnumerable<TItem>> GetByQueryAsync(
    QueryDefinition queryDefinition,
    CancellationToken cancellationToken = default);
```

Does the added complexity internally add a lot of external benefit, in other words - is it worth it? What's the risk and exposure, how many edge cases will we encounter, how many consumers will actually use it? Also, how does this differ from the `GetAsync` with the `Expression<Func<TItem, bool>>` predicate? These expressions are already available, and are correctly converted to the appropriate corresponding SQL query statements. It kind of feels like we're trying to over engineer this, do you agree?

**Comment by mumby0168** [comment]
> Hi @mumby0168,
> 
> 
> 
> I guess my initial thoughts are that we already expose two overloads of the `GetByQueryAsync` APIs:
> 
> 
> 
> ```csharp
> 
> ValueTask<IEnumerable<TItem>> GetByQueryAsync(
> 
>     string query,
> 
>     CancellationToken cancellationToken = default);
> 
> 
> 
> ValueTask<IEnumerable<TItem>> GetByQueryAsync(
> 
>     QueryDefinition queryDefinition,
> 
>     CancellationToken cancellationToken = default);
> 
> ```
> 
> 
> 
> Does the added complexity internally add a lot of external benefit, in other words - is it worth it? What's the risk and exposure, how many edge cases will we encounter, how many consumers will actually use it? Also, how does this differ from the `GetAsync` with the `Expression<Func<TItem, bool>>` predicate? These expressions are already available, and are correctly converted to the appropriate corresponding SQL query statements. It kind of feels like we're trying to over engineer this, do you agree?

Hi yeah I've thought about this and I think you very well may be right, I liked the idea of been able to use some extra bits such as .OrderBy but I suppose as a client there is nothing stopping you just injecting the container provider and then performing this query yourself for these niche scenarios. 

Only problem with the SQL queries and the options above is in my team certainly we make use of the in memory option a lot for integration tests and these would break doing either of the above. But from this libraries point of view I agree with you 👍🏼

**Comment by mumby0168** [comment]
This is now supported via the specification pattern.
