### ISSUE TITLE
Exception when Item doesn't exist

### ISSUE THREAD

**Issue by burdier** [IEvangelist/azure-cosmos-dotnet-repository#99]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.CosmosRepository).

I'm  using this  cool wrap along with mediataR,  when I try to get an Item using  GetAsync and  it does not exist 
I got this exception: Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: 18f33e01-f625-4439-ab27-f2ff7f6be36b; Reason: ()

**To Reproduce**
```csharp 
        public async Task<GetUserResponse> Handle(GetUserRequest request, CancellationToken cancellationToken)
        { 
            var user = await _db.GetAsync(request.Id.ToString(), cancellationToken: cancellationToken);
            if (user is null)
            {
                throw new ArgumentException();
            } 
            return user.Adapt<GetUserResponse>();
        }
```

**Expected behavior**
GetAsync is supposed to be a null  when not match the type

**Actual behavior**
Raising a exception

**Environment summary**
SDK Version: 2.3.0
OS Version (MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by mumby0168** [comment]
Hi there this is the standard behaviour of the azure cosmos sdk it throws a `CosmosException` with the `StatusCode` field set to `HttpStatusCode.NotFound`. The library aims to not deviate too much from the implementation of the sdk only enhance it. One thing that I have done and could be useful to you is to right an extension method as below which will offer you what you need for the time being. We could maybe address adding this to the library but I am not sure we would.

```csharp
public static class RepositoryExtensions
{
    public static async ValueTask<T?> GetOrNullAsync<T>(this IRepository<T> repository, string id,
        string? partitionKey, CancellationToken cancellationToken = default) where T : class, IItem
    {
        try
        {
            return await repository.GetAsync(id, partitionKey, cancellationToken);
         }
         catch (CosmosException e) when (e.StatusCode == HttpStatusCode.NotFound)
         {
              return null;
         }
     }
}
```

**Comment by burdier** [comment]
Thanks
